#!/usr/bin/env python3
"""scripts/build-behavioral-matrix.py — reads probes/classified/behavioral.yaml
(its ONLY input) and writes comparisons/behavioral.md — one section per
requirement, a table of rate-with-count results per model, and a separate
declared-skips table. A sibling of scripts/build-probe-matrix.py, with the
identical three-mode CLI/exit-code contract and a shared HEADER constant so the
writer and `--check`'s drift comparator can never independently drift apart.

    python3 scripts/build-behavioral-matrix.py             # regenerate + print a counted summary
    python3 scripts/build-behavioral-matrix.py --check      # drift-check against disk
    python3 scripts/build-behavioral-matrix.py --selftest   # run the embedded fixture battery

Exit codes: 0 clean, 1 problems recorded (--check/--selftest only), 2 bad
invocation or malformed input.

Rate rendering (unlike scripts/build-probe-matrix.py's glyph vocabulary):
behavioral results are RATE-valued, not boolean — every rendered rate is the
integer match-over-comparisons pair with its percentage beside it (e.g.
"4/4 (100.0%)"), never a symbol standing for a boolean. `checked:`/
`evidence_through:` are carried straight from the classified YAML, never
wall-clock — idempotent regeneration is byte-stable.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CLASSIFIED_PATH = REPO_ROOT / "probes" / "classified" / "behavioral.yaml"
OUTPUT_PATH = REPO_ROOT / "comparisons" / "behavioral.md"

HEADER = (
    "<!-- GENERATED by scripts/build-behavioral-matrix.py from\n"
    "     probes/classified/behavioral.yaml — do not edit by hand. Regenerate\n"
    "     with `python3 scripts/build-behavioral-matrix.py`. -->\n"
    "\n"
    "# probes/classified/behavioral.yaml, rendered\n"
)


def _fail(code: int, msg: str) -> None:
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def _load_yaml(path: Path, required_key: str) -> dict:
    try:
        text = Path(path).read_text()
    except OSError as e:
        _fail(2, f"cannot read {path}: {e}")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        _fail(2, f"{path} is not valid YAML: {e}")
    if not isinstance(data, dict) or required_key not in data:
        _fail(2, f"{path}: expected a top-level `{required_key}:` key")
    return data


def load_classified(path: Path = CLASSIFIED_PATH) -> dict:
    return _load_yaml(path, "cells")


def requirement_order(cells: list[dict]) -> list[str]:
    """Section order — first-occurrence scan of `requirement` across the
    classified YAML's own row order (already deterministic per
    classify-behavioral.py's own sort)."""
    order: list[str] = []
    seen: set[str] = set()
    for c in cells:
        r = c["requirement"]
        if r not in seen:
            seen.add(r)
            order.append(r)
    return order


def render_rate(cell: dict) -> str:
    """The rate rendered as its integer pair, with the percentage beside it
    when computable (comparisons > 0) — never a bare percentage, and never a
    symbol standing for a boolean (D-02's own must_haves truth)."""
    if cell.get("rate_pct") is None:
        return cell["rate"]
    return f"{cell['rate']} ({cell['rate_pct']}%)"


def render_matrix(classified: dict) -> str:
    cells = classified["cells"]
    skips = classified.get("skips") or []
    checked = classified.get("checked")
    evidence_through = classified.get("evidence_through")

    requirements = requirement_order(cells)

    lines: list[str] = [HEADER.rstrip("\n"), ""]
    lines.append(f"`checked:` {checked}  ")
    lines.append(f"`evidence_through:` {evidence_through}")
    lines.append("")

    for req in requirements:
        req_cells = [c for c in cells if c["requirement"] == req]
        lines.append(f"## {req} ({len(req_cells)} cell{'s' if len(req_cells) != 1 else ''})")
        lines.append("")
        lines.append("| Model | Design | Repeats | Rate | Verdict | Expected (citation) | probe_ids |")
        lines.append("|---|---|---|---|---|---|---|")
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['model']} | {c['design']} | {c['repeats']} | {render_rate(c)} | "
                f"{c['verdict']} | {expected_cell} | {len(c['probe_ids'])} |"
            )
        lines.append("")

    lines.append("## Declared Skips")
    lines.append("")
    if skips:
        lines.append("| Model | Param | Requirement | Reason | Citation |")
        lines.append("|---|---|---|---|---|")
        for s in skips:
            citation = s.get("cited_probe_id") or s.get("cited_source") or "—"
            lines.append(
                f"| {s.get('model')} | {s.get('param')} | {s.get('requirement')} | "
                f"{s.get('reason')} | {citation} |"
            )
    else:
        lines.append("None yet — no cell has been declared skipped.")
    lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def regenerate(path: Path = CLASSIFIED_PATH) -> tuple[str, dict]:
    classified = load_classified(path)
    text = render_matrix(classified)
    return text, classified


def check_generated_drift(path: Path = CLASSIFIED_PATH) -> tuple[int, int]:
    checks = 0
    problems = 0
    checks += 1
    expected_text, _classified = regenerate(path)
    if not OUTPUT_PATH.exists():
        problems += 1
        print(f"FAIL drift: {OUTPUT_PATH} does not exist — run the generator", file=sys.stderr)
    else:
        actual_text = OUTPUT_PATH.read_text()
        if actual_text != expected_text:
            problems += 1
            print(
                f"FAIL drift: {OUTPUT_PATH} does not match a fresh render of {CLASSIFIED_PATH} "
                "— it was hand-edited or is stale (rule 3)",
                file=sys.stderr,
            )
    return checks, problems


def print_summary(classified: dict) -> None:
    cells = classified["cells"]
    skips = classified.get("skips") or []
    tally: dict[str, int] = {}
    for c in cells:
        tally[c["verdict"]] = tally.get(c["verdict"], 0) + 1
    print(f"cells read: {len(cells)}")
    print(f"requirements (sections): {len(requirement_order(cells))}")
    print(f"declared skips: {len(skips)}")
    for verdict in sorted(tally):
        print(f"  {verdict}: {tally[verdict]}")


# -----------------------------------------------------------------------------------
# --selftest — embedded fixtures, no external test framework.
# -----------------------------------------------------------------------------------


def selftest() -> tuple[int, int]:
    problems = 0
    cases = 0

    fixture_cells = [
        {
            "cell_id": "m1--p--v--default", "requirement": "calibration", "design": "control",
            "model": "m1", "vendor": "anthropic", "mode": "default", "param": "p", "value": "v",
            "repeats": 5, "comparisons": 4, "matches": 4, "rate": "4/4", "rate_pct": 100.0,
            "distinct_outputs": 1, "verdict": "deterministic", "expected": "expect x",
            "expected_source": "prereg:x", "probe_ids": ["a", "b", "c", "d", "e"], "ancillary": {}, "note": None,
        },
        {
            "cell_id": "m2--p--v--default", "requirement": "calibration", "design": "control",
            "model": "m2", "vendor": "openai", "mode": "default", "param": "p", "value": "v",
            "repeats": 5, "comparisons": 4, "matches": 0, "rate": "0/4", "rate_pct": 0.0,
            "distinct_outputs": 5, "verdict": "varies", "expected": "expect y",
            "expected_source": "prereg:y", "probe_ids": ["f", "g", "h", "i", "j"], "ancillary": {}, "note": None,
        },
        {
            "cell_id": "m1--q--v--default", "requirement": "BHV-02", "design": "repeats",
            "model": "m1", "vendor": "anthropic", "mode": "default", "param": "q", "value": "v",
            "repeats": 5, "comparisons": 4, "matches": 2, "rate": "2/4", "rate_pct": 50.0,
            "distinct_outputs": 3, "verdict": "partial", "expected": "expect z",
            "expected_source": "phase11:z", "probe_ids": ["k", "l", "m", "n", "o"], "ancillary": {}, "note": None,
        },
    ]

    # --- requirement_order: first-occurrence, deduplicated ---
    cases += 1
    order = requirement_order(fixture_cells)
    if order != ["calibration", "BHV-02"]:
        problems += 1
        print(f"FAIL requirement_order: expected ['calibration', 'BHV-02'], got {order}", file=sys.stderr)

    # --- render_rate: full match and zero match both render as the integer
    #     pair with a percentage beside it ---
    cases += 1
    full = render_rate(fixture_cells[0])
    zero = render_rate(fixture_cells[1])
    if full != "4/4 (100.0%)":
        problems += 1
        print(f"FAIL render_rate(full match): expected '4/4 (100.0%)', got {full!r}", file=sys.stderr)
    if zero != "0/4 (0.0%)":
        problems += 1
        print(f"FAIL render_rate(zero match): expected '0/4 (0.0%)', got {zero!r}", file=sys.stderr)

    # --- render_rate: no rate_pct falls back to the bare rate string ---
    cases += 1
    no_pct_cell = {"rate": "0/0", "rate_pct": None}
    if render_rate(no_pct_cell) != "0/0":
        problems += 1
        print(f"FAIL render_rate(no pct): expected '0/0', got {render_rate(no_pct_cell)!r}", file=sys.stderr)

    # --- render_matrix: header shared with HEADER, first line matches ---
    cases += 1
    fixture_doc = {"checked": "2026-09-03", "evidence_through": None, "cells": fixture_cells, "skips": []}
    rendered = render_matrix(fixture_doc)
    if not rendered.startswith(HEADER.split("\n")[0]):
        problems += 1
        print("FAIL render_matrix: rendered output does not start with the shared HEADER", file=sys.stderr)
    if "scripts/build-behavioral-matrix.py" not in rendered:
        problems += 1
        print("FAIL render_matrix: HEADER must name this generator script", file=sys.stderr)

    # --- render_matrix: deterministic, byte-identical for identical input (idempotency) ---
    cases += 1
    first = render_matrix(fixture_doc)
    second = render_matrix(fixture_doc)
    if first != second:
        problems += 1
        print("FAIL render_matrix: expected byte-identical output for identical input", file=sys.stderr)

    # --- render_matrix: every rate is rendered as an integer pair with a
    #     percentage, never a bare percentage and never a boolean-like symbol ---
    cases += 1
    if "4/4 (100.0%)" not in rendered or "0/4 (0.0%)" not in rendered or "2/4 (50.0%)" not in rendered:
        problems += 1
        print("FAIL render_matrix: expected every fixture rate rendered as its integer pair with a percentage", file=sys.stderr)
    if "True" in rendered or "False" in rendered:
        problems += 1
        print("FAIL render_matrix: a YAML-boolean-looking token leaked into the rendered matrix", file=sys.stderr)

    # --- render_matrix: sections named per requirement, with their own cell count ---
    cases += 1
    if "## calibration (2 cells)" not in rendered or "## BHV-02 (1 cell)" not in rendered:
        problems += 1
        print("FAIL render_matrix: expected requirement-sectioned headings with cell counts", file=sys.stderr)

    # --- render_matrix: a doc with declared skips renders a populated skips table ---
    cases += 1
    skip_doc = {
        "checked": "2026-09-03", "evidence_through": None, "cells": fixture_cells,
        "skips": [{"model": "m3", "param": "r", "mode": "default", "requirement": "BHV-03", "reason": "fixture-reason", "cited_probe_id": "x--y--z--default--aaaa", "cited_source": None}],
    }
    skip_rendered = render_matrix(skip_doc)
    if "fixture-reason" not in skip_rendered or "x--y--z--default--aaaa" not in skip_rendered:
        problems += 1
        print("FAIL render_matrix: a declared skip was not rendered in the Declared Skips table", file=sys.stderr)

    # --- render_matrix: no declared skips renders an explicit "None yet" line ---
    cases += 1
    if "None yet" not in rendered:
        problems += 1
        print("FAIL render_matrix: expected an explicit 'None yet' line for a skip-free doc", file=sys.stderr)

    return cases, problems


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="build-behavioral-matrix.py",
        usage="build-behavioral-matrix.py [--check | --selftest]",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        cases, problems = selftest()
        print(f"{cases} cases run, {problems} problem(s)")
        return 1 if problems else 0

    if args.check:
        checks, problems = check_generated_drift()
        print(f"{problems} problem(s)")
        return 1 if problems else 0

    text, classified = regenerate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)
    print_summary(classified)
    return 0


if __name__ == "__main__":
    sys.exit(main())
