#!/usr/bin/env python3
"""scripts/build-behavioral-matrix.py — reads probes/classified/behavioral.yaml
(its ONLY input) and writes comparisons/behavioral.md — one section per
requirement, a table of rate-with-count results per model, and a separate
declared-skips table. A sibling of scripts/build-probe-matrix.py, with the
identical three-mode CLI/exit-code contract and a shared HEADER constant so the
writer and `--check`'s drift comparator can never independently drift apart.

    python3 scripts/build-behavioral-matrix.py             # regenerate + print a counted summary
    python3 scripts/build-behavioral-matrix.py --check      # drift-check against disk
    python3 scripts/build-behavioral-matrix.py --selftest   # run the embedded fixture battery

Exit codes: 0 clean, 1 problems recorded (--check/--selftest only), 2 bad
invocation or malformed input.

Rate rendering (unlike scripts/build-probe-matrix.py's glyph vocabulary):
behavioral results are RATE-valued, not boolean — every rendered rate is the
integer match-over-comparisons pair with its percentage beside it (e.g.
"4/4 (100.0%)"), never a symbol standing for a boolean. `checked:`/
`evidence_through:` are carried straight from the classified YAML, never
wall-clock — idempotent regeneration is byte-stable.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CLASSIFIED_PATH = REPO_ROOT / "probes" / "classified" / "behavioral.yaml"
OUTPUT_PATH = REPO_ROOT / "comparisons" / "behavioral.md"

HEADER = (
    "<!-- GENERATED by scripts/build-behavioral-matrix.py from\n"
    "     probes/classified/behavioral.yaml — do not edit by hand. Regenerate\n"
    "     with `python3 scripts/build-behavioral-matrix.py`. -->\n"
    "\n"
    "# probes/classified/behavioral.yaml, rendered\n"
)


def _fail(code: int, msg: str) -> None:
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def _load_yaml(path: Path, required_key: str) -> dict:
    try:
        text = Path(path).read_text()
    except OSError as e:
        _fail(2, f"cannot read {path}: {e}")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        _fail(2, f"{path} is not valid YAML: {e}")
    if not isinstance(data, dict) or required_key not in data:
        _fail(2, f"{path}: expected a top-level `{required_key}:` key")
    return data


def load_classified(path: Path = CLASSIFIED_PATH) -> dict:
    return _load_yaml(path, "cells")


def requirement_order(cells: list[dict]) -> list[str]:
    """Section order — first-occurrence scan of `requirement` across the
    classified YAML's own row order (already deterministic per
    classify-behavioral.py's own sort)."""
    order: list[str] = []
    seen: set[str] = set()
    for c in cells:
        r = c["requirement"]
        if r not in seen:
            seen.add(r)
            order.append(r)
    return order


def render_rate(cell: dict) -> str:
    """The rate rendered as its integer pair, with the percentage beside it
    when computable (comparisons > 0) — never a bare percentage, and never a
    symbol standing for a boolean (D-02's own must_haves truth)."""
    if cell.get("rate_pct") is None:
        return cell["rate"]
    return f"{cell['rate']} ({cell['rate_pct']}%)"


def render_section(req_cells: list[dict]) -> list[str]:
    """Column layout dispatched by DESIGN, not one shared table for every
    requirement (12-03): `control` keeps the original repeats/rate/verdict
    layout; `repeats` (BHV-02/D-03) adds its own Comparisons/Distinct Outputs
    columns explicitly rather than reusing `control`'s `Repeats` header for a
    different meaning; `seed-pairs` (BHV-01) gets Pairs/Calls/Effect Control
    columns entirely of its own — a reader must never mistake a
    default-config-repeatability substitute cell's rate for a real
    temperature-0 result, or a seed pair-match rate for a flat repeat-vs-
    baseline rate. Every cell in one requirement section shares one design in
    practice (`calibration`->control, `BHV-01`->seed-pairs, `BHV-02`->
    repeats); a MIXED-design section fails loud rather than silently
    rendering the first cell's own column shape for every row."""
    designs = {c["design"] for c in req_cells}
    if len(designs) != 1:
        _fail(2, f"a requirement section must share one design, got {sorted(designs)}")
    design = next(iter(designs))

    if design == "seed-pairs":
        lines = ["| Model | Pairs | Calls | Rate | Effect Control | Verdict | Expected (citation) | probe_ids |",
                  "|---|---|---|---|---|---|---|---|"]
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            ec = c.get("seed_effect_control") or {}
            ec_cell = f"{ec.get('result')} ({ec.get('probe_id')})" if ec else "—"
            lines.append(
                f"| {c['model']} | {c['pairs']} | {c['calls']} | {render_rate(c)} | "
                f"{ec_cell} | {c['verdict']} | {expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    if design == "repeats":
        lines = ["| Model | Repeats | Comparisons | Rate | Distinct Outputs | Verdict | Expected (citation) | probe_ids |",
                  "|---|---|---|---|---|---|---|---|"]
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['model']} | {c['repeats']} | {c['comparisons']} | {render_rate(c)} | "
                f"{c['distinct_outputs']} | {c['verdict']} | {expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    if design == "control":
        lines = ["| Model | Design | Repeats | Rate | Verdict | Expected (citation) | probe_ids |",
                  "|---|---|---|---|---|---|---|"]
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['model']} | {c['design']} | {c['repeats']} | {render_rate(c)} | "
                f"{c['verdict']} | {expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    if design == "single-stop":
        lines = ["| Model | Triggering Length | Control Length | Stop Token in Text | "
                  "Truncation Verdict | Finish-Reason Honest | Expected (citation) | probe_ids |",
                  "|---|---|---|---|---|---|---|---|"]
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['model']} | {c['triggering_text_length']} | {c['control_text_length']} | "
                f"{c['stop_token_in_triggering_text']} | {c['truncation_verdict']} | "
                f"{c['finish_reason_honest']} | {expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    if design == "single-candidates":
        lines = ["| Model | Requested n | Returned Count | State | Expected (citation) | probe_ids |",
                  "|---|---|---|---|---|---|"]
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['model']} | {c['requested_n']} | {c['returned_count']} | {c['state']} | "
                f"{expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    if design == "tier-audit":
        # 12-05: `tier-audit` rows for BOTH the eight-vendor service-tier
        # audit (BHV-06's own `service-tier-audit` param) and the D-07
        # documentation-drift annex (DeepSeek's `thinking-object`, Qwen's
        # `reasoning-effort` — distinct param values) share one requirement
        # (BHV-06) and one design, so they land in this SAME call — split
        # into two rendered subsections by `param` rather than requiring a
        # second requirement label, matching the plan's own "a service-tier
        # section ... Render the annex cells in their own section" ask.
        audit_cells = [c for c in req_cells if c["param"] == "service-tier-audit"]
        annex_cells = [c for c in req_cells if c["param"] != "service-tier-audit"]
        lines: list[str] = []

        lines.append(f"### Service-tier audit ({len(audit_cells)} cell{'s' if len(audit_cells) != 1 else ''})")
        lines.append("")
        lines.append(
            "| Vendor | Model | Request Value | Request Field Path | Response Field Path | "
            "Response Value | Response Present | Echo Relation | Source | probe_ids |"
        )
        lines.append("|---|---|---|---|---|---|---|---|---|---|")
        for c in audit_cells:
            source = "audited" if c.get("audited_from_existing_evidence") else "fired"
            request_value = c.get("request_value")
            request_cell = "omitted" if request_value is None else request_value
            lines.append(
                f"| {c['vendor']} | {c['model']} | {request_cell} | {c.get('request_field_path')} | "
                f"{c.get('response_field_path')} | {c.get('response_value')} | {c.get('response_present')} | "
                f"{c.get('echo_relation')} | {source} | {len(c['probe_ids'])} |"
            )
        lines.append("")

        anthropic_asymmetry_rows = [
            c for c in audit_cells
            if c["vendor"] == "anthropic" and c.get("response_top_level_present") is not None
            and c.get("value") not in ("trap",)
        ]
        if anthropic_asymmetry_rows:
            r = anthropic_asymmetry_rows[0]
            confirmed = r["response_present"] == "present" and r["response_top_level_present"] == "absent"
            verdict = "CONFIRMED" if confirmed else "REFUTED"
            lines.append(
                f"**Anthropic asymmetry {verdict}:** the nested `{r.get('response_field_path')}` "
                f"reads `{r.get('response_present')}` while the response top level's own "
                f"`service_tier` reads `{r.get('response_top_level_present')}` "
                f"(probe_id `{r['probe_ids'][0]}`)."
            )
            lines.append("")

        lines.append(f"### Documentation-drift annex ({len(annex_cells)} cell{'s' if len(annex_cells) != 1 else ''})")
        lines.append("")
        lines.append("| Vendor | Model | Param | Request Value | Echo Relation | Registry Assumption | Expected (citation) | probe_ids |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for c in annex_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['vendor']} | {c['model']} | {c['param']} | {c.get('request_value')} | "
                f"{c.get('echo_relation')} | {c.get('note') or '—'} | {expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    if design == "single-logprobs":
        lines = ["| Model | Mode | Present | Token Entries | Alternatives Honored | State | "
                  "Settles (phase 11 probe_id) | Expected (citation) | probe_ids |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for c in req_cells:
            expected_cell = f"{c['expected']} ({c['expected_source']})"
            lines.append(
                f"| {c['model']} | {c['mode']} | {c['logprobs_present']} | {c['logprobs_token_entries']} | "
                f"{c['logprobs_alternatives_honored']} | {c['state']} | {c.get('settles_probe_id') or '—'} | "
                f"{expected_cell} | {len(c['probe_ids'])} |"
            )
        return lines

    _fail(2, f"render_section: unhandled design {design!r}")


def render_matrix(classified: dict) -> str:
    cells = classified["cells"]
    skips = classified.get("skips") or []
    checked = classified.get("checked")
    evidence_through = classified.get("evidence_through")

    requirements = requirement_order(cells)

    lines: list[str] = [HEADER.rstrip("\n"), ""]
    lines.append(f"`checked:` {checked}  ")
    lines.append(f"`evidence_through:` {evidence_through}")
    lines.append("")

    for req in requirements:
        req_cells = [c for c in cells if c["requirement"] == req]
        lines.append(f"## {req} ({len(req_cells)} cell{'s' if len(req_cells) != 1 else ''})")
        lines.append("")
        lines.extend(render_section(req_cells))
        lines.append("")

    lines.append("## Declared Skips")
    lines.append("")
    if skips:
        lines.append("| Model | Param | Requirement | Reason | Citation |")
        lines.append("|---|---|---|---|---|")
        for s in skips:
            citation = s.get("cited_probe_id") or s.get("cited_source") or "—"
            lines.append(
                f"| {s.get('model')} | {s.get('param')} | {s.get('requirement')} | "
                f"{s.get('reason')} | {citation} |"
            )
    else:
        lines.append("None yet — no cell has been declared skipped.")
    lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def regenerate(path: Path = CLASSIFIED_PATH) -> tuple[str, dict]:
    classified = load_classified(path)
    text = render_matrix(classified)
    return text, classified


def check_generated_drift(path: Path = CLASSIFIED_PATH) -> tuple[int, int]:
    checks = 0
    problems = 0
    checks += 1
    expected_text, _classified = regenerate(path)
    if not OUTPUT_PATH.exists():
        problems += 1
        print(f"FAIL drift: {OUTPUT_PATH} does not exist — run the generator", file=sys.stderr)
    else:
        actual_text = OUTPUT_PATH.read_text()
        if actual_text != expected_text:
            problems += 1
            print(
                f"FAIL drift: {OUTPUT_PATH} does not match a fresh render of {CLASSIFIED_PATH} "
                "— it was hand-edited or is stale (rule 3)",
                file=sys.stderr,
            )
    return checks, problems


def print_summary(classified: dict) -> None:
    """Tallies the primary judgement field per row -- `verdict` for the
    rate-based designs, `truncation_verdict` for single-stop, `state` for
    single-candidates/single-logprobs, `echo_relation` for tier-audit
    (12-05: this design carries neither a `verdict` nor a `state` key)."""
    cells = classified["cells"]
    skips = classified.get("skips") or []
    tally: dict[str, int] = {}
    for c in cells:
        key = c.get("verdict") or c.get("truncation_verdict") or c.get("state") or c.get("echo_relation")
        tally[key] = tally.get(key, 0) + 1
    print(f"cells read: {len(cells)}")
    print(f"requirements (sections): {len(requirement_order(cells))}")
    print(f"declared skips: {len(skips)}")
    for verdict in sorted(tally):
        print(f"  {verdict}: {tally[verdict]}")


# -----------------------------------------------------------------------------------
# --selftest — embedded fixtures, no external test framework.
# -----------------------------------------------------------------------------------


def selftest() -> tuple[int, int]:
    problems = 0
    cases = 0

    fixture_cells = [
        {
            "cell_id": "m1--p--v--default", "requirement": "calibration", "design": "control",
            "model": "m1", "vendor": "anthropic", "mode": "default", "param": "p", "value": "v",
            "repeats": 5, "comparisons": 4, "matches": 4, "rate": "4/4", "rate_pct": 100.0,
            "distinct_outputs": 1, "verdict": "deterministic", "expected": "expect x",
            "expected_source": "prereg:x", "probe_ids": ["a", "b", "c", "d", "e"], "ancillary": {}, "note": None,
        },
        {
            "cell_id": "m2--p--v--default", "requirement": "calibration", "design": "control",
            "model": "m2", "vendor": "openai", "mode": "default", "param": "p", "value": "v",
            "repeats": 5, "comparisons": 4, "matches": 0, "rate": "0/4", "rate_pct": 0.0,
            "distinct_outputs": 5, "verdict": "varies", "expected": "expect y",
            "expected_source": "prereg:y", "probe_ids": ["f", "g", "h", "i", "j"], "ancillary": {}, "note": None,
        },
        {
            "cell_id": "m1--q--v--default", "requirement": "BHV-02", "design": "repeats",
            "model": "m1", "vendor": "anthropic", "mode": "default", "param": "q", "value": "v",
            "repeats": 5, "comparisons": 4, "matches": 2, "rate": "2/4", "rate_pct": 50.0,
            "distinct_outputs": 3, "verdict": "partial", "expected": "expect z",
            "expected_source": "phase11:z", "probe_ids": ["k", "l", "m", "n", "o"], "ancillary": {}, "note": None,
        },
    ]

    # --- requirement_order: first-occurrence, deduplicated ---
    cases += 1
    order = requirement_order(fixture_cells)
    if order != ["calibration", "BHV-02"]:
        problems += 1
        print(f"FAIL requirement_order: expected ['calibration', 'BHV-02'], got {order}", file=sys.stderr)

    # --- render_rate: full match and zero match both render as the integer
    #     pair with a percentage beside it ---
    cases += 1
    full = render_rate(fixture_cells[0])
    zero = render_rate(fixture_cells[1])
    if full != "4/4 (100.0%)":
        problems += 1
        print(f"FAIL render_rate(full match): expected '4/4 (100.0%)', got {full!r}", file=sys.stderr)
    if zero != "0/4 (0.0%)":
        problems += 1
        print(f"FAIL render_rate(zero match): expected '0/4 (0.0%)', got {zero!r}", file=sys.stderr)

    # --- render_rate: no rate_pct falls back to the bare rate string ---
    cases += 1
    no_pct_cell = {"rate": "0/0", "rate_pct": None}
    if render_rate(no_pct_cell) != "0/0":
        problems += 1
        print(f"FAIL render_rate(no pct): expected '0/0', got {render_rate(no_pct_cell)!r}", file=sys.stderr)

    # --- render_matrix: header shared with HEADER, first line matches ---
    cases += 1
    fixture_doc = {"checked": "2026-09-03", "evidence_through": None, "cells": fixture_cells, "skips": []}
    rendered = render_matrix(fixture_doc)
    if not rendered.startswith(HEADER.split("\n")[0]):
        problems += 1
        print("FAIL render_matrix: rendered output does not start with the shared HEADER", file=sys.stderr)
    if "scripts/build-behavioral-matrix.py" not in rendered:
        problems += 1
        print("FAIL render_matrix: HEADER must name this generator script", file=sys.stderr)

    # --- render_matrix: deterministic, byte-identical for identical input (idempotency) ---
    cases += 1
    first = render_matrix(fixture_doc)
    second = render_matrix(fixture_doc)
    if first != second:
        problems += 1
        print("FAIL render_matrix: expected byte-identical output for identical input", file=sys.stderr)

    # --- render_matrix: every rate is rendered as an integer pair with a
    #     percentage, never a bare percentage and never a boolean-like symbol ---
    cases += 1
    if "4/4 (100.0%)" not in rendered or "0/4 (0.0%)" not in rendered or "2/4 (50.0%)" not in rendered:
        problems += 1
        print("FAIL render_matrix: expected every fixture rate rendered as its integer pair with a percentage", file=sys.stderr)
    if "True" in rendered or "False" in rendered:
        problems += 1
        print("FAIL render_matrix: a YAML-boolean-looking token leaked into the rendered matrix", file=sys.stderr)

    # --- render_matrix: sections named per requirement, with their own cell count ---
    cases += 1
    if "## calibration (2 cells)" not in rendered or "## BHV-02 (1 cell)" not in rendered:
        problems += 1
        print("FAIL render_matrix: expected requirement-sectioned headings with cell counts", file=sys.stderr)

    # --- render_matrix: a doc with declared skips renders a populated skips table ---
    cases += 1
    skip_doc = {
        "checked": "2026-09-03", "evidence_through": None, "cells": fixture_cells,
        "skips": [{"model": "m3", "param": "r", "mode": "default", "requirement": "BHV-03", "reason": "fixture-reason", "cited_probe_id": "x--y--z--default--aaaa", "cited_source": None}],
    }
    skip_rendered = render_matrix(skip_doc)
    if "fixture-reason" not in skip_rendered or "x--y--z--default--aaaa" not in skip_rendered:
        problems += 1
        print("FAIL render_matrix: a declared skip was not rendered in the Declared Skips table", file=sys.stderr)

    # --- render_matrix: no declared skips renders an explicit "None yet" line ---
    cases += 1
    if "None yet" not in rendered:
        problems += 1
        print("FAIL render_matrix: expected an explicit 'None yet' line for a skip-free doc", file=sys.stderr)

    # --- render_section: design=seed-pairs gets its own Pairs/Calls/Effect
    #     Control columns, distinct from both control's and repeats' layouts ---
    cases += 1
    seed_pair_cells = [{
        "cell_id": "m3--seed--42--default", "requirement": "BHV-01", "design": "seed-pairs",
        "model": "m3", "vendor": "openai", "mode": "default", "param": "seed", "value": 42,
        "pairs": 5, "calls": 10, "matching_pairs": 5, "rate": "5/5", "rate_pct": 100.0,
        "verdict": "deterministic", "seed_effect_control": {"result": "matched", "probe_id": "m3--seed--99--default--aaaa"},
        "expected": "expect w", "expected_source": "docs-claims:seed/openai",
        "probe_ids": ["p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8", "p9", "p10"],
        "ancillary": {}, "note": "a full rate whose effect control also matched",
    }]
    seed_section = render_section(seed_pair_cells)
    seed_rendered = "\n".join(seed_section)
    if "Pairs" not in seed_rendered or "Calls" not in seed_rendered or "Effect Control" not in seed_rendered:
        problems += 1
        print("FAIL render_section(seed-pairs): expected Pairs/Calls/Effect Control columns", file=sys.stderr)
    if "5/5 (100.0%)" not in seed_rendered or "matched" not in seed_rendered:
        problems += 1
        print("FAIL render_section(seed-pairs): expected the rendered rate and effect-control result", file=sys.stderr)

    # --- render_section: design=repeats gets Comparisons/Distinct Outputs
    #     columns, never the seed-pairs Pairs/Calls layout ---
    cases += 1
    repeats_section = render_section([fixture_cells[2]])
    repeats_rendered = "\n".join(repeats_section)
    if "Comparisons" not in repeats_rendered or "Distinct Outputs" not in repeats_rendered:
        problems += 1
        print("FAIL render_section(repeats): expected Comparisons/Distinct Outputs columns", file=sys.stderr)
    if "Pairs" in repeats_rendered or "Effect Control" in repeats_rendered:
        problems += 1
        print("FAIL render_section(repeats): must not carry the seed-pairs Pairs/Effect Control columns", file=sys.stderr)

    # --- render_section: a mixed-design section fails loud rather than
    #     silently rendering the first cell's own column shape for every row ---
    cases += 1
    try:
        render_section([fixture_cells[0], fixture_cells[2]])  # control + repeats mixed
        problems += 1
        print("FAIL render_section: a mixed-design section was not rejected", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL render_section(mixed design): expected exit 2, got {e.code}", file=sys.stderr)

    # --- render_section: design=single-stop (12-04) gets its own
    #     Triggering/Control Length + Truncation Verdict + Finish-Reason
    #     Honest columns, distinct from every rate-based design's layout ---
    cases += 1
    single_stop_cells = [{
        "cell_id": "m4--stop-truncation--triggering--default", "requirement": "BHV-03", "design": "single-stop",
        "model": "m4", "vendor": "anthropic", "mode": "default", "param": "stop-truncation", "value": "triggering",
        "stop_token": "Thursday", "triggering_text_length": 25, "control_text_length": 56,
        "stop_token_in_triggering_text": False, "truncation_verdict": "stop-honored", "finish_reason_honest": "honest",
        "expected": "expect v", "expected_source": "docs-claims:stop/anthropic",
        "probe_ids": ["p1", "p2"], "ancillary": {}, "note": None,
    }]
    single_stop_section = "\n".join(render_section(single_stop_cells))
    if "Truncation Verdict" not in single_stop_section or "Finish-Reason Honest" not in single_stop_section:
        problems += 1
        print("FAIL render_section(single-stop): expected Truncation Verdict/Finish-Reason Honest columns", file=sys.stderr)
    if "stop-honored" not in single_stop_section or "honest" not in single_stop_section:
        problems += 1
        print("FAIL render_section(single-stop): expected the rendered verdict and honesty judgement", file=sys.stderr)

    # --- render_section: design=single-candidates gets its own Requested
    #     n/Returned Count/State columns ---
    cases += 1
    single_candidates_cells = [{
        "cell_id": "m5--n--2--default", "requirement": "BHV-04", "design": "single-candidates",
        "model": "m5", "vendor": "openai", "mode": "default", "param": "n", "value": 2,
        "requested_n": 2, "returned_count": 2, "state": "accepted-honored", "evidence": "candidate-count",
        "expected": "expect w", "expected_source": "docs-claims:n/openai",
        "probe_ids": ["p3"], "ancillary": {}, "note": None,
    }]
    single_candidates_section = "\n".join(render_section(single_candidates_cells))
    if "Requested n" not in single_candidates_section or "Returned Count" not in single_candidates_section:
        problems += 1
        print("FAIL render_section(single-candidates): expected Requested n/Returned Count columns", file=sys.stderr)
    if "accepted-honored" not in single_candidates_section:
        problems += 1
        print("FAIL render_section(single-candidates): expected the rendered state", file=sys.stderr)

    # --- render_section: design=single-logprobs gets its own Present/Token
    #     Entries/Settles columns, including the phase-11 citation link ---
    cases += 1
    single_logprobs_cells = [{
        "cell_id": "m6--logprobs-reverify--combined--default", "requirement": "BHV-05", "design": "single-logprobs",
        "model": "m6", "vendor": "qwen", "mode": "default", "param": "logprobs-reverify", "value": "combined",
        "requested_top_logprobs": 3, "logprobs_present": True, "logprobs_token_entries": 47,
        "logprobs_alternatives_honored": True, "state": "accepted-honored", "evidence": "logprobs-content",
        "settles_probe_id": "m6--top-logprobs--3--default--deadbeef",
        "expected": "expect u", "expected_source": "docs-claims:top-logprobs/qwen",
        "probe_ids": ["p4"], "ancillary": {}, "note": None,
    }]
    single_logprobs_section = "\n".join(render_section(single_logprobs_cells))
    if "Token Entries" not in single_logprobs_section or "Settles" not in single_logprobs_section:
        problems += 1
        print("FAIL render_section(single-logprobs): expected Token Entries/Settles columns", file=sys.stderr)
    if "m6--top-logprobs--3--default--deadbeef" not in single_logprobs_section:
        problems += 1
        print("FAIL render_section(single-logprobs): expected the settled phase-11 probe_id rendered", file=sys.stderr)

    # --- render_section: design=tier-audit (12-05) splits into a
    #     "Service-tier audit" subsection (param=service-tier-audit) and a
    #     "Documentation-drift annex" subsection (any other param) even
    #     though both share one requirement (BHV-06) and one design ---
    cases += 1
    tier_audit_cells = [
        {
            "cell_id": "m7--service-tier-audit--auto--default", "requirement": "BHV-06", "design": "tier-audit",
            "model": "m7", "vendor": "anthropic", "mode": "default", "param": "service-tier-audit", "value": "auto",
            "request_field_path": "service_tier", "request_value": "auto",
            "response_field_path": "usage.service_tier", "response_value": "standard",
            "response_present": "present", "echo_relation": "translated", "rejection_names_field": None,
            "response_top_level_present": "absent", "response_top_level_value": None,
            "audited_from_existing_evidence": False, "cited_probe_id": None,
            "expected": "expect t", "expected_source": "docs-claims:service-tier/anthropic",
            "probe_ids": ["p5"], "ancillary": {}, "note": None,
        },
        {
            "cell_id": "m7--service-tier-audit--trap--default", "requirement": "BHV-06", "design": "tier-audit",
            "model": "m7", "vendor": "anthropic", "mode": "default", "param": "service-tier-audit", "value": "trap",
            "request_field_path": "service_tier", "request_value": "standard",
            "response_field_path": None, "response_value": None,
            "response_present": "absent", "echo_relation": "rejected", "rejection_names_field": True,
            "response_top_level_present": None, "response_top_level_value": None,
            "audited_from_existing_evidence": False, "cited_probe_id": None,
            "expected": "expect trap", "expected_source": "docs-claims:service-tier/anthropic",
            "probe_ids": ["p6"], "ancillary": {}, "note": None,
        },
        {
            "cell_id": "m8--thinking-object--enabled--default", "requirement": "BHV-06", "design": "tier-audit",
            "model": "m8", "vendor": "dseek", "mode": "default", "param": "thinking-object", "value": "enabled",
            "request_field_path": "thinking", "request_value": {"type": "enabled"},
            "response_field_path": "thinking", "response_value": None,
            "response_present": "absent", "echo_relation": "dropped", "rejection_names_field": None,
            "response_top_level_present": None, "response_top_level_value": None,
            "audited_from_existing_evidence": False, "cited_probe_id": None,
            "expected": "expect d", "expected_source": "docs-claims:anthropic-thinking-object/dseek",
            "probe_ids": ["p7"], "ancillary": {}, "note": "contradicts a registry assumption",
        },
    ]
    tier_audit_section = "\n".join(render_section(tier_audit_cells))
    if "Service-tier audit (2 cells)" not in tier_audit_section:
        problems += 1
        print("FAIL render_section(tier-audit): expected a Service-tier audit subsection with the right count", file=sys.stderr)
    if "Documentation-drift annex (1 cell)" not in tier_audit_section:
        problems += 1
        print("FAIL render_section(tier-audit): expected a Documentation-drift annex subsection with the right count", file=sys.stderr)
    if "CONFIRMED" not in tier_audit_section or "usage.service_tier" not in tier_audit_section:
        problems += 1
        print("FAIL render_section(tier-audit): expected the Anthropic asymmetry stated as CONFIRMED", file=sys.stderr)
    if "contradicts a registry assumption" not in tier_audit_section:
        problems += 1
        print("FAIL render_section(tier-audit): expected the annex row's registry-assumption note rendered", file=sys.stderr)
    if "rejected" not in tier_audit_section:
        problems += 1
        print("FAIL render_section(tier-audit): expected the trap row's rejected echo_relation rendered", file=sys.stderr)

    # --- render_matrix: a doc mixing all six designs across their own
    #     requirement sections renders every one without crashing, and each
    #     section heading states its own cell count (12-04's three new
    #     designs alongside the three pre-existing ones) ---
    cases += 1
    mixed_doc = {
        "checked": "2026-09-03", "evidence_through": None,
        "cells": fixture_cells + single_stop_cells + single_candidates_cells + single_logprobs_cells,
        "skips": [],
    }
    mixed_rendered = render_matrix(mixed_doc)
    for heading in ("## BHV-03 (1 cell)", "## BHV-04 (1 cell)", "## BHV-05 (1 cell)"):
        if heading not in mixed_rendered:
            problems += 1
            print(f"FAIL render_matrix(mixed six-design doc): expected heading {heading!r}", file=sys.stderr)

    # --- render_matrix: a doc adding tier-audit (BHV-06) alongside the
    #     other designs still renders every section, one heading per
    #     requirement (tier-audit's own two param-split subsections live
    #     INSIDE that one BHV-06 section, not as separate `##` headings) ---
    cases += 1
    seven_design_doc = {
        "checked": "2026-09-03", "evidence_through": None,
        "cells": fixture_cells + single_stop_cells + single_candidates_cells + single_logprobs_cells + tier_audit_cells,
        "skips": [],
    }
    seven_design_rendered = render_matrix(seven_design_doc)
    if "## BHV-06 (3 cells)" not in seven_design_rendered:
        problems += 1
        print("FAIL render_matrix(seven-design doc): expected a single '## BHV-06 (3 cells)' heading", file=sys.stderr)

    return cases, problems


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="build-behavioral-matrix.py",
        usage="build-behavioral-matrix.py [--check | --selftest]",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        cases, problems = selftest()
        print(f"{cases} cases run, {problems} problem(s)")
        return 1 if problems else 0

    if args.check:
        checks, problems = check_generated_drift()
        print(f"{problems} problem(s)")
        return 1 if problems else 0

    text, classified = regenerate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)
    print_summary(classified)
    return 0


if __name__ == "__main__":
    sys.exit(main())
