#!/usr/bin/env python3
"""Generate references/index.md and comparisons/benchmarks.md from the frontmatter of every ref note.

Sibling of build-tool-index.py, same rule (methodology 3): a hand-kept catalog drifts from
the notes it describes, and you find out when it's already wrong.

    python3 scripts/build-refs-index.py            # write the catalog + benchmark matrix
    python3 scripts/build-refs-index.py --check    # lint only, write nothing

--check enforces the honesty properties the library exists for:

  1. required frontmatter present, `kind` / `read_depth` inside the vocabulary
  2. a ref cited elsewhere in the repo whose note says `read_depth: unread` — the guard
     against an abstract skim hardening into a citation
  3. a `references/<key>.md` link with no note behind it
  4. (warning only) a note with no `bears_on` — recorded but not yet used anywhere

1-3 exit non-zero. Deliberately strict about 2: it is the failure this library was built
to prevent.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REFS = ROOT / "references"
PAPERS = REFS / "papers"
CARDS = REFS / "cards"
OUT = REFS / "index.md"
BENCH_OUT = ROOT / "comparisons" / "benchmarks.md"

# Files under references/ that are not sources.
NOT_A_NOTE = {"index.md", "README.md", "log.md"}

REQUIRED = ("key", "title", "year", "kind", "read_depth", "retrieved")

# Fixed vocabularies. Keep small; a new value is a deliberate decision, not a typo.
KIND_ORDER = {
    "benchmark": 0,        # ships tasks + a verifier we could run or borrow
    "empirical-study": 1,  # ran something, reports measurements
    "method": 2,           # proposes a technique or framework
    "critique": 3,         # argues something else is wrong
    "survey": 4,           # characterizes a field, usually without running it
}
# Order = increasing trust in what the note claims about the paper.
READ_DEPTH_ORDER = {"full": 0, "extract": 1, "abstract": 2, "unread": 3}

# Benchmark-only frontmatter. Order defines the matrix columns.
BENCH_KEYS = [
    "task_shape", "task_count", "task_source", "verifier",
    "ambiguity_construction", "user_simulator", "metrics",
    "contamination_posture", "headroom",
]


def read_frontmatter(path: Path) -> dict | None:
    """Return the YAML frontmatter of a markdown file, or None if it has none.

    Mirrors the same function in build-tool-index.py. Kept duplicated rather than
    factored into a shared module: ten lines, and the two scripts validate different
    schemas — coupling them would mean one script's vocabulary change breaking the other.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    data = yaml.safe_load(text[4:end])
    return data if isinstance(data, dict) else None


def collect() -> list[dict]:
    notes = []
    if not PAPERS.is_dir():
        return notes
    for path in sorted(PAPERS.glob("*.md")):
        if path.name in NOT_A_NOTE or path.name.startswith("_"):
            continue
        fm = read_frontmatter(path)
        if fm is None:
            print(f"warn: {path.relative_to(ROOT)} has no frontmatter", file=sys.stderr)
            continue
        fm["_path"] = path
        notes.append(fm)
    return sorted(
        notes,
        key=lambda n: (
            KIND_ORDER.get(n.get("kind"), 9),
            READ_DEPTH_ORDER.get(n.get("read_depth"), 9),
            str(n.get("key", "")),
        ),
    )


def citing_files(key: str) -> list[Path]:
    """Markdown files outside references/ that mention this ref key.

    Generated files are skipped: a catalog listing every note, `unread` ones included, is
    not a citation. Only prose that leans on a source counts.
    """
    hits = []
    for path in ROOT.rglob("*.md"):
        rel = path.relative_to(ROOT)
        if rel.parts[0] in ("refs", "upstream", ".git", ".planning"):
            continue
        text = path.read_text(encoding="utf-8")
        if "GENERATED by scripts/" in text:
            continue
        if key in text:
            hits.append(rel)
    return hits


# A card note's schema is deliberately NOT the paper one (ADR-0034). `read_depth` and
# `kind` describe literature; a vendor card's honesty fields are which models it covers,
# when the vendor published/updated it, when we read it, and — because a card is rewritten
# in place at one URL — what snapshot backs the quotes a report depends on.
CARD_REQUIRED = ("key", "vendor", "title", "models_covered", "retrieved", "url", "snapshot")


def collect_cards() -> list[dict]:
    cards = []
    if not CARDS.is_dir():
        return cards
    for path in sorted(CARDS.glob("*.md")):
        if path.name in NOT_A_NOTE or path.name.startswith("_"):
            continue
        fm = read_frontmatter(path)
        if fm is None:
            print(f"warn: {path.relative_to(ROOT)} has no frontmatter", file=sys.stderr)
            continue
        fm["_path"] = path
        cards.append(fm)
    return sorted(cards, key=lambda c: str(c.get("key", "")))


def check_cards(cards: list[dict]) -> int:
    problems = 0
    for c in cards:
        rel = c["_path"].relative_to(ROOT)
        missing = [k for k in CARD_REQUIRED if not c.get(k)]
        if missing:
            print(f"ERROR: {rel} missing {missing}", file=sys.stderr)
            problems += 1
        if c.get("key") and c["key"] != c["_path"].stem:
            print(
                f"ERROR: {rel} key '{c['key']}' != filename stem '{c['_path'].stem}'",
                file=sys.stderr,
            )
            problems += 1
        snap = str(c.get("snapshot") or "")
        if snap and "web.archive.org" not in snap:
            print(
                f"ERROR: {rel} snapshot must be an archive URL (a card is rewritten in "
                f"place, so the live URL is not evidence): {snap}",
                file=sys.stderr,
            )
            problems += 1
    return problems


def check(notes: list[dict]) -> int:
    problems = 0
    keys = {n.get("key") for n in notes}

    for n in notes:
        rel = n["_path"].relative_to(ROOT)
        missing = [k for k in REQUIRED if k not in n]
        if missing:
            print(f"ERROR: {rel} missing {missing}", file=sys.stderr)
            problems += 1
            continue
        if n["_path"].stem != n["key"]:
            print(
                f"ERROR: {rel} has key '{n['key']}' — must equal the filename stem "
                f"'{n['_path'].stem}' (the key is the citekey)",
                file=sys.stderr,
            )
            problems += 1
        if n["kind"] not in KIND_ORDER:
            print(
                f"ERROR: {rel} kind '{n['kind']}' not in {sorted(KIND_ORDER)}",
                file=sys.stderr,
            )
            problems += 1
        if n["read_depth"] not in READ_DEPTH_ORDER:
            print(
                f"ERROR: {rel} read_depth '{n['read_depth']}' not in "
                f"{sorted(READ_DEPTH_ORDER)}",
                file=sys.stderr,
            )
            problems += 1

        # The load-bearing check: unread sources must not be cited as evidence.
        if n.get("read_depth") == "unread":
            cited_by = citing_files(n["key"])
            if cited_by:
                where = ", ".join(str(p) for p in cited_by)
                print(
                    f"ERROR: {rel} is read_depth: unread but cited in {where} "
                    f"— read it or remove the citation",
                    file=sys.stderr,
                )
                problems += 1

        if not n.get("bears_on"):
            print(f"warn: {rel} has no bears_on — recorded but unused", file=sys.stderr)

    # Dangling references/papers/<key>.md and references/cards/<key>.md links anywhere in
    # the repo. Split on the FULL prefix, not on "references/": since ADR-0034 the notes
    # live one level down, so a token starting "papers/…" would trip the "/" guard below
    # and the check would go silently blind — the failure mode this scan exists to prevent.
    card_keys = {c.get("key") for c in collect_cards()}
    for prefix, valid in (("references/papers/", keys), ("references/cards/", card_keys)):
      for path in ROOT.rglob("*.md"):
        if path.relative_to(ROOT).parts[0] in ("upstream", ".git", ".planning"):
            continue
        for token in path.read_text(encoding="utf-8").split(prefix)[1:]:
            name = token.split(".md")[0].split(")")[0].split("`")[0].strip()
            if not name or "/" in name or name in ("index", "README", "log", "pdf"):
                continue
            if "<" in name or ">" in name:
                continue  # a placeholder in the docs, e.g. references/<key>.md — not a link
            if name.startswith("_"):
                continue  # templates are not notes
            if any(c.isspace() for c in name):
                # Prose or a diagram that merely mentions the directory, not a citation:
                # a citekey never contains whitespace. Without this, README's layout tree
                # ("references/  one note per source read …") is read as a link to a note named
                # after the whole annotation. The established fix for PROSE is to backtick
                # the mention (the split on "`" above), but that is unavailable inside a
                # fenced code block — hence the guard rather than another backtick.
                continue
            if name not in valid:
                print(
                    f"ERROR: {path.relative_to(ROOT)} links {prefix}{name}.md — no such note",
                    file=sys.stderr,
                )
                problems += 1
    return problems


def _fmt(value: object) -> str:
    """Render a frontmatter value as a table cell. `·` means not recorded, not 'no'."""
    if value is None:
        return "·"
    if value is True:
        return "✓"
    if value is False:
        return "✗"
    if isinstance(value, list):
        return ", ".join(f"`{v}`" for v in value) if value else "·"
    return str(value)


def render(notes: list[dict], cards: list[dict] | None = None) -> str:
    newest = max((str(n.get("retrieved", "")) for n in notes), default="")
    lines = [
        "# Reference index",
        "",
        "<!-- GENERATED by scripts/build-refs-index.py — do not edit by hand. -->",
        "<!-- Edit the frontmatter of the notes in references/papers/ or",
        "     references/cards/, then re-run the script. -->",
        "",
        f"Every source with a note. **Papers** ({len(notes)}) below, grouped by kind, then",
        f"**vendor model cards** ({len(cards or [])}) — a separate half because a card is not",
        "literature: it has no `read_depth` to declare, and it is rewritten in place at one",
        "URL, so each card note carries the archive snapshot its quotes rest on (ADR-0034).",
        f"Newest retrieved: `{newest}`.",
        "",
        "`read` is the honesty column, mirroring `depth` in "
        "[`../comparisons/tools.md`](../comparisons/tools.md): **full** means the paper was "
        "read end to end; **extract** means a tool answered questions against it and nobody "
        "read the whole thing; **abstract** means only the abstract; **unread** means the "
        "source is recorded as a lead and nothing in this repo may cite it. "
        "`build-refs-index.py --check` fails if an `unread` source is cited anywhere.",
        "",
        "`Peer` distinguishes peer-reviewed venues from preprints — a 2026 arXiv preprint is "
        "a lead, not a settled result, and should not outweigh our own measurements without "
        "reason.",
        "",
        "`Cites` is field-acceptance **context, never a quality weight** — fetched by "
        "`scripts/fetch-citations.py --write` (Semantic Scholar; each note carries its "
        "`citations_at` date). It is age-confounded (recent preprints cannot have accumulated "
        "citations) and validity-independent (the most-cited member here, SWE-bench, later had "
        "68.3% of its items removed as invalid). **·** = no arXiv id, count not applicable.",
        "",
    ]
    for kind in sorted(KIND_ORDER, key=lambda k: KIND_ORDER[k]):
        group = [n for n in notes if n.get("kind") == kind]
        if not group:
            continue
        lines += [
            f"## {kind}",
            "",
            "| Source | Year | Venue | Peer | read | Cites | Bears on | What it does to our claims |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for n in group:
            link = f"[{n['key']}](papers/{n['_path'].name})"
            bears = _fmt(n.get("bears_on"))
            cites = n.get("citations")
            cites_cell = str(cites).split(" — ")[0] if cites else "·"
            lines.append(
                f"| {link} | {n.get('year', '·')} | {n.get('venue', '·')} | "
                f"{_fmt(n.get('peer_reviewed'))} | {n['read_depth']} | {cites_cell} | {bears} | "
                f"{n.get('verdict', '·')} |"
            )
        lines.append("")

    counts: dict[str, int] = {}
    for n in notes:
        counts[n["read_depth"]] = counts.get(n["read_depth"], 0) + 1
    summary = " · ".join(f"{v} {k}" for k, v in sorted(counts.items(), key=lambda kv: READ_DEPTH_ORDER.get(kv[0], 9)))
    lines += [f"**{len(notes)} papers** — {summary}.", ""]
    lines += render_cards_section(cards or [])
    return "\n".join(lines)


def render_cards_section(cards: list[dict]) -> list[str]:
    """The index's second half. Columns are the card schema's honesty fields — what the
    card covers, when the vendor last touched it, when we read it, and the snapshot."""
    if not cards:
        return ["## Vendor model cards", "", "*None yet.*", ""]
    lines = [
        "## Vendor model cards",
        "",
        "| Card | Vendor | Covers | Published | Last updated | Retrieved | Snapshot |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in cards:
        covers = _fmt(c.get("models_covered"))
        lines.append(
            f"| [{c['key']}](cards/{c['_path'].name}) | {c.get('vendor', '·')} | {covers} | "
            f"{_fmt(c.get('published'))} | {_fmt(c.get('last_updated'))} | "
            f"{_fmt(c.get('retrieved'))} | [archived]({c['snapshot']}) |"
        )
    lines.append("")
    return lines


def render_benchmarks(notes: list[dict]) -> str:
    bench = [n for n in notes if n.get("kind") == "benchmark"]
    lines = [
        "# Benchmark matrix",
        "",
        "<!-- GENERATED by scripts/build-refs-index.py — do not edit by hand. -->",
        "<!-- Edit the frontmatter of the benchmark notes in references/, then re-run. -->",
        "",
        "Benchmarks we could borrow a task from, or borrow a metric from. Cells: **·** means "
        "not recorded — it is *not* a no.",
        "",
        "Two columns exist because of scars, and they are the ones to read first:",
        "",
        "- **headroom** — does a current frontier model still fail some of these tasks? "
        "Methodology 5d: an instrument a competent baseline saturates cannot measure a "
        "difference. exp-02's trap set was proven fails-closed and still useless for its "
        "main purpose.",
        "- **contamination** — a task in the training corpus is *more* likely to saturate, "
        "because both arms partly recall the answer and the difference vanishes. "
        "`canary` / `time-windowed` / `private-holdout` are defences; `none` is a warning.",
        "",
        "| Benchmark | " + " | ".join(k.replace("_", " ") for k in BENCH_KEYS) + " | Note |",
        "|---|" + "---|" * (len(BENCH_KEYS) + 1),
    ]
    for n in bench:
        cells = [_fmt(n.get(k)) for k in BENCH_KEYS]
        link = f"[{n['key']}](../references/papers/{n['_path'].name})"
        lines.append(f"| {n.get('title', n['key'])} | " + " | ".join(cells) + f" | {link} |")
    lines += ["", f"**{len(bench)} benchmarks.**", ""]
    return "\n".join(lines)


def main() -> int:
    notes = collect()
    cards = collect_cards()
    if not notes:
        print("no paper notes with frontmatter found", file=sys.stderr)
        return 1

    if "--check" in sys.argv:
        problems = check(notes) + check_cards(cards)
        print(f"{len(notes)} papers + {len(cards)} cards checked, {problems} problem(s)")
        return 1 if problems else 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    BENCH_OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(notes, cards), encoding="utf-8")
    BENCH_OUT.write_text(render_benchmarks(notes), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(notes)} papers, {len(cards)} cards")
    print(f"wrote {BENCH_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
