#!/usr/bin/env python3
"""scripts/build-docs-vs-wire.py — reads probes/docs-claims.yaml (the first-party
vendor documentation claims registry, Phase 11.1) AND probes/classified/contract-sweep.yaml
(Phase 11's classified wire evidence), joins them at (param, model) granularity, and writes
comparisons/docs-vs-wire.md — the docs-vs-wire confrontation.

Deliberately NOT an extension of scripts/build-probe-matrix.py (MTX-02 requires that
generator to read the classified YAML alone); this one reads two hand/generated inputs
plus probes/harness/models.yaml (model/vendor order) and probes/inventory.yaml (group/row
order and the swept+excluded param universe) — never a third hand-maintained list.

    python3 scripts/build-docs-vs-wire.py             # regenerate + print a counted summary
    python3 scripts/build-docs-vs-wire.py --check      # drift-check against disk
    python3 scripts/build-docs-vs-wire.py --selftest   # run the embedded fixture battery

Exit codes: 0 clean, 1 problems recorded (--check/--selftest only), 2 bad invocation,
malformed input, or a structural registry defect (missing claim, unrecognized vocabulary).

Rule 3 (generated, never hand-edited): a shared HEADER string constant is used by both
the writer and `--check`'s drift comparator. `checked:`/`evidence_through:` are carried
straight from the two inputs, never wall-clock — idempotent regeneration is byte-stable
(D-01's post-hoc-dating discipline).

Anti-overclaiming (D-05, load-bearing): a verdict speaks ONLY to the existence/acceptance
facet. `documented_range`, `documented_allowed_values`, `documented_default`, and
`conditionality` never enter verdict_for() and never appear in a matrix cell — they render
only in the "Documented facets awaiting behavioral test" section (Phase 12's rule-5a feed).
A probe that fired one value cannot corroborate a range; the code makes that structurally
impossible rather than merely avoided by convention.
"""
from __future__ import annotations

import argparse
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_CLAIMS_PATH = REPO_ROOT / "probes" / "docs-claims.yaml"
CLASSIFIED_PATH = REPO_ROOT / "probes" / "classified" / "contract-sweep.yaml"
MODELS_PATH = REPO_ROOT / "probes" / "harness" / "models.yaml"
INVENTORY_PATH = REPO_ROOT / "probes" / "inventory.yaml"
OUTPUT_PATH = REPO_ROOT / "comparisons" / "docs-vs-wire.md"

HEADER = (
    "<!-- GENERATED by scripts/build-docs-vs-wire.py from\n"
    "     probes/docs-claims.yaml (first-party vendor documentation claims) and\n"
    "     probes/classified/contract-sweep.yaml (Phase 11's classified wire\n"
    "     evidence) — do not edit by hand. Regenerate with\n"
    "     `python3 scripts/build-docs-vs-wire.py`. -->\n"
    "\n"
    "# probes/docs-claims.yaml x probes/classified/contract-sweep.yaml, confronted\n"
)

# The five closed verdicts (ROADMAP criterion 5) — every rendered cell carries exactly
# one, never a default. Distinct glyphs, one per verdict.
VERDICTS: tuple[str, ...] = (
    "docs-corroborated",
    "docs-contradicted",
    "docs-undecidable",
    "docs-untested",
    "docs-silent",
)

GLYPHS: dict[str, str] = {
    "docs-corroborated": "✓",
    "docs-contradicted": "✗",
    "docs-undecidable": "◐",
    "docs-untested": "·",
    "docs-silent": "—",
}

LEGEND_ROWS = [
    (GLYPHS["docs-corroborated"], "docs-corroborated", "the wire evidence matches the documented contract"),
    (GLYPHS["docs-contradicted"], "docs-contradicted", "the wire evidence contradicts the documented contract"),
    (GLYPHS["docs-undecidable"], "docs-undecidable", "the wire accepted the value with no honor-discriminating signal in this response"),
    (GLYPHS["docs-untested"], "docs-untested", "no wire evidence exists for this pair yet — skipped, needs-review, or never probed (includes every excluded inventory row)"),
    (GLYPHS["docs-silent"], "docs-silent", "the docs list the parameter but state nothing about its contract — claim status resolved before wire state"),
]

# Reduction precedence when a (param, model) pair carries several wire cells whose
# individual verdicts differ (D-04's must_haves: "the reduction applies the fixed
# precedence docs-contradicted > docs-corroborated > docs-undecidable > docs-untested").
# docs-silent is excluded — a docs-silent claim's cells are ALWAYS uniformly docs-silent
# (claim status resolves first), so it never enters a mixed reduction.
VERDICT_PRECEDENCE: tuple[str, ...] = (
    "docs-contradicted",
    "docs-corroborated",
    "docs-undecidable",
    "docs-untested",
)

# The four facet fields a verdict may NEVER speak to (D-05, T-11.1-11) — they render
# only in the facets section. Deliberately does not include documented_name/
# documented_type (descriptive, not a range/behavior a single-point probe could
# overclaim).
FACET_FIELDS: tuple[str, ...] = (
    "documented_range",
    "documented_allowed_values",
    "documented_default",
    "conditionality",
)

CLAIM_STATUSES = frozenset({"documented", "absent-from-docs", "docs-silent"})
ACCEPTED_FAMILY = frozenset({"accepted-honored", "accepted-ignored", "silently-translated"})
WIRE_STATES = ACCEPTED_FAMILY | frozenset(
    {"rejected", "accepted-unverified", "skipped", "needs-review", "unfired"}
)


def _fail(code: int, msg: str) -> None:
    """Print a diagnostic and raise SystemExit(code) — the fail-loud path this module
    shares with scripts/build-probe-matrix.py, scripts/classify-probes.py, and
    probes/check-docs-claims.py."""
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def _load_yaml(path: Path, required_key: str) -> dict:
    try:
        text = Path(path).read_text()
    except OSError as e:
        _fail(2, f"cannot read {path}: {e}")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        _fail(2, f"{path} is not valid YAML: {e}")
    if not isinstance(data, dict) or required_key not in data:
        _fail(2, f"{path}: expected a top-level `{required_key}:` key")
    return data


def load_docs_claims(path: Path = DOCS_CLAIMS_PATH) -> dict:
    return _load_yaml(path, "claims")


def load_classified(path: Path = CLASSIFIED_PATH) -> dict:
    return _load_yaml(path, "cells")


def load_models(path: Path = MODELS_PATH) -> dict:
    return _load_yaml(path, "models")


def load_inventory(path: Path = INVENTORY_PATH) -> dict:
    return _load_yaml(path, "params")


def verdict_for(claim_status: str, wire_state: str | None) -> str:
    """Resolve ONE verdict from a claim's documented_status and a single wire cell's
    state. Claim status resolves FIRST: a claim the docs never asserted anything about
    renders its own verdict whatever the wire says. Otherwise the wire state decides,
    closed to the vocabulary above — anything outside it fails loud rather than
    defaulting (T-11.1-10). Speaks only to existence/acceptance; never reads a fact
    about a value's permitted range or shape (D-05, T-11.1-11)."""
    if claim_status not in CLAIM_STATUSES:
        _fail(
            2,
            f"verdict_for: unrecognized documented_status {claim_status!r} — "
            f"closed vocabulary is {sorted(CLAIM_STATUSES)}",
        )
    if claim_status == "docs-silent":
        return "docs-silent"
    if wire_state is None or wire_state in ("skipped", "needs-review", "unfired"):
        return "docs-untested"
    if wire_state == "accepted-unverified":
        return "docs-undecidable"
    if wire_state in ACCEPTED_FAMILY:
        return "docs-corroborated" if claim_status == "documented" else "docs-contradicted"
    if wire_state == "rejected":
        return "docs-contradicted" if claim_status == "documented" else "docs-corroborated"
    _fail(
        2,
        f"verdict_for: unrecognized wire state {wire_state!r} — "
        f"closed vocabulary is {sorted(WIRE_STATES)}",
    )


def glyph_for(verdict: str) -> str:
    if verdict not in GLYPHS:
        _fail(2, f"glyph_for: verdict {verdict!r} is outside the rendered glyph vocabulary {sorted(GLYPHS)}")
    return GLYPHS[verdict]


def reduce_verdicts(verdicts: list[str]) -> str:
    """Reduce several cell-level verdicts to one, by VERDICT_PRECEDENCE. Never
    averages, never takes the first — the highest-precedence verdict present wins."""
    for v in VERDICT_PRECEDENCE:
        if v in verdicts:
            return v
    _fail(
        2,
        f"reduce_verdicts: no verdict in {verdicts!r} matches the known precedence "
        f"{VERDICT_PRECEDENCE} — empty or unrecognized verdict list",
    )


def resolve_pair_verdict(claim_status: str, cells: list[dict]) -> tuple[str, bool, list[dict]]:
    """One (param, model) pair may carry several wire cells (one per mode/value the
    row's axis expands to) or none at all (every excluded inventory row, and any swept
    row whose cell was never emitted — EDGE DOCP-04). A docs-silent claim renders
    docs-silent uniformly regardless of cell count or content — there was no documented
    assertion to confront. Otherwise every cell resolves its own verdict via
    verdict_for() and the pair reduces via VERDICT_PRECEDENCE; `non_unanimous` is True
    when the contributing cells' individual verdicts disagreed before reduction, so the
    contradictions section can list every one of them rather than averaging away a
    divergence."""
    if claim_status == "docs-silent":
        return "docs-silent", False, cells
    if not cells:
        return verdict_for(claim_status, None), False, cells
    cell_verdicts = [verdict_for(claim_status, c["state"]) for c in cells]
    reduced = reduce_verdicts(cell_verdicts)
    non_unanimous = len(set(cell_verdicts)) > 1
    return reduced, non_unanimous, cells


def build_rows(inventory: dict, models_doc: dict, docs_claims: dict, classified: dict) -> list[dict]:
    """Granularity is (param, model) (D-04). For every param in inventory.yaml (SWEPT
    AND EXCLUDED rows both in scope, CONTEXT.md's Phase Boundary) and every model in
    models.yaml, resolve vendor = model.vendor, look up the claim at (param, vendor),
    and gather every classified cell with that (param, model). A missing claim is a
    fail-loud structural error, not a blank — the validator guarantees completeness, so
    an absence means the inputs are inconsistent."""
    claims_idx = {(c["param"], c["vendor"]): c for c in docs_claims["claims"]}
    cells_idx: dict[tuple, list] = defaultdict(list)
    for c in classified["cells"]:
        cells_idx[(c["param"], c["model"])].append(c)

    model_list = [m["slug"] for m in models_doc["models"]]
    vendor_of = {m["slug"]: m["vendor"] for m in models_doc["models"]}

    rows: list[dict] = []
    for param_row in inventory["params"]:
        param = param_row["id"]
        for model in model_list:
            vendor = vendor_of[model]
            claim = claims_idx.get((param, vendor))
            if claim is None:
                _fail(
                    2,
                    f"build_rows: no claim for param={param!r} vendor={vendor!r} — "
                    "probes/docs-claims.yaml is incomplete for this (param, vendor) pair",
                )
            cells = cells_idx.get((param, model), [])
            verdict, non_unanimous, contributing = resolve_pair_verdict(claim["documented_status"], cells)
            rows.append(
                {
                    "param": param,
                    "model": model,
                    "vendor": vendor,
                    "claim": claim,
                    "cells": contributing,
                    "verdict": verdict,
                    "non_unanimous": non_unanimous,
                }
            )
    return rows


def render_limitation_note(docs_claims: dict, classified: dict) -> list[str]:
    claims_checked = docs_claims.get("checked")
    classified_checked = classified.get("checked")
    evidence_through = classified.get("evidence_through")
    lines: list[str] = []
    lines.append(
        f"**Post-hoc confrontation, dated.** The first-party documentation claims "
        f"registry (`probes/docs-claims.yaml`, `checked: {claims_checked}`) was "
        f"transcribed AFTER Phase 11's wire evidence (`probes/classified/contract-sweep.yaml`, "
        f"`checked: {classified_checked}`, `evidence_through: {evidence_through}`) had "
        "already fired. For every verdict below confronting a Phase 11 cell, this "
        "confrontation is therefore post-hoc — a dated retrospective read, not a "
        "prediction made in advance of the evidence it judges. For Phase 12's behavioral "
        "runs, which have not yet fired, the same claims registry is a genuine prior: a "
        "documented expected value stated before any wire evidence exists to confront it "
        "(methodology rule 5a). Per methodology rule 1a, docs claims are TESTIMONY — a "
        "vendor's own stated account of its own API — ranked below the probes' OBSERVED "
        "wire evidence; a `docs-contradicted` verdict below means the wire disagreed with "
        "what the vendor's own docs say, not that the docs are wrong in any absolute sense."
    )
    lines.append("")
    return lines


def render_legend() -> list[str]:
    lines: list[str] = ["## Legend", "", "| Glyph | Verdict | Note |", "|---|---|---|"]
    for glyph, verdict, note in LEGEND_ROWS:
        lines.append(f"| {glyph} | {verdict} | {note} |")
    lines.append("")
    return lines


def render_matrices(rows: list[dict], inventory: dict, models_doc: dict) -> list[str]:
    model_list = [m["slug"] for m in models_doc["models"]]
    row_by_key = {(r["param"], r["model"]): r for r in rows}
    param_group = {p["id"]: p["group"] for p in inventory["params"]}
    param_order = [p["id"] for p in inventory["params"]]
    groups_sorted = sorted(inventory["groups"], key=lambda g: g["order"])

    lines: list[str] = ["## Matrices", ""]
    for g in groups_sorted:
        gid = g["id"]
        params_in_group = [p for p in param_order if param_group.get(p) == gid]
        if not params_in_group:
            continue
        lines.append(f"### {g.get('title', gid)}")
        lines.append("")
        header = ["Parameter"] + model_list
        lines.append("| " + " | ".join(header) + " |")
        lines.append("|" + "---|" * len(header))
        for param in params_in_group:
            row_cells = [param]
            for model in model_list:
                r = row_by_key[(param, model)]
                row_cells.append(glyph_for(r["verdict"]))
            lines.append("| " + " | ".join(row_cells) + " |")
        lines.append("")
    return lines


def render_contradictions(rows: list[dict]) -> list[str]:
    """Every docs-contradicted (param, model) pair, with the claim's verbatim quote,
    its source_ref, and a representative contributing cell's probe_id and http_status —
    Phase 13's PROM-01 input. Then every non-unanimous pair, with each contributing
    cell's mode/value/state/probe_id listed — a divergence is surfaced, never averaged
    away."""
    lines: list[str] = ["## Contradictions", ""]
    contradicted = [r for r in rows if r["verdict"] == "docs-contradicted"]
    lines.append(
        f"{len(contradicted)} `(param, model)` pair(s) where the wire evidence "
        "contradicted the documented contract — Phase 13's PROM-01 input."
    )
    lines.append("")
    if contradicted:
        lines.append("| Parameter | Model | Quote | source_ref | probe_id | http_status |")
        lines.append("|---|---|---|---|---|---|")
        for r in contradicted:
            claim = r["claim"]
            rep_cell = None
            for c in r["cells"]:
                if verdict_for(claim["documented_status"], c["state"]) == "docs-contradicted":
                    rep_cell = c
                    break
            probe_id = rep_cell.get("probe_id") if rep_cell else "—"
            http_status = rep_cell.get("http_status") if rep_cell else "—"
            quote = str(claim.get("quote") or "—").replace("|", "\\|").replace("\n", " ")
            lines.append(
                f"| {r['param']} | {r['model']} | {quote} | {claim.get('source_ref')} | "
                f"{probe_id} | {http_status} |"
            )
    else:
        lines.append("None.")
    lines.append("")

    non_unanimous = [r for r in rows if r["non_unanimous"]]
    lines.append("### Non-unanimous pairs")
    lines.append("")
    lines.append(
        f"{len(non_unanimous)} `(param, model)` pair(s) whose contributing cells "
        "disagreed before reduction."
    )
    lines.append("")
    if non_unanimous:
        lines.append("| Parameter | Model | Reduced verdict | Contributing cells (mode, value, state, probe_id) |")
        lines.append("|---|---|---|---|")
        for r in non_unanimous:
            contrib = "; ".join(
                f"({c['mode']}, {c['value']}, {c['state']}, {c.get('probe_id') or '—'})" for c in r["cells"]
            )
            lines.append(f"| {r['param']} | {r['model']} | {r['verdict']} | {contrib} |")
    else:
        lines.append("None.")
    lines.append("")
    return lines


def render_docs_silent(docs_claims: dict) -> list[str]:
    lines: list[str] = ["## Docs-silent", ""]
    silent = [c for c in docs_claims["claims"] if c.get("documented_status") == "docs-silent"]
    lines.append(
        f"{len(silent)} claim(s) — the vendor's own docs list the parameter but state "
        "nothing about its range, default, allowed values, or conditionality."
    )
    lines.append("")
    if silent:
        lines.append("| Parameter | Vendor | searched_surface | source_ref |")
        lines.append("|---|---|---|---|")
        for c in silent:
            surface = str(c.get("searched_surface") or "—").replace("|", "\\|").replace("\n", " ")
            lines.append(f"| {c['param']} | {c['vendor']} | {surface} | {c.get('source_ref')} |")
    else:
        lines.append("None.")
    lines.append("")
    return lines


def _facet_cell(value) -> str:
    if value is None:
        return "—"
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_facets_feed(docs_claims: dict) -> list[str]:
    """One row per claim carrying a non-null facet — Phase 12's rule-5a expected-value
    feed. These values never entered a verdict above (D-05); this is the ONLY place
    they render."""
    lines: list[str] = ["## Documented facets awaiting behavioral test", ""]
    facet_claims = [c for c in docs_claims["claims"] if any(c.get(f) is not None for f in FACET_FIELDS)]
    lines.append(
        f"{len(facet_claims)} claim(s) carry a documented range, allowed-values, "
        "default, or conditionality fact a single-point probe cannot corroborate — "
        "every verdict above speaks only to existence/acceptance (D-05); this is Phase "
        "12's rule-5a expected-value feed."
    )
    lines.append("")
    if facet_claims:
        lines.append("| Parameter | Vendor | Range | Allowed values | Default | Conditionality | source_ref |")
        lines.append("|---|---|---|---|---|---|---|")
        for c in facet_claims:
            lines.append(
                f"| {c['param']} | {c['vendor']} | {_facet_cell(c.get('documented_range'))} | "
                f"{_facet_cell(c.get('documented_allowed_values'))} | {_facet_cell(c.get('documented_default'))} | "
                f"{_facet_cell(c.get('conditionality'))} | {c.get('source_ref')} |"
            )
    else:
        lines.append("None.")
    lines.append("")
    return lines


def render_report(rows: list[dict], docs_claims: dict, classified: dict, inventory: dict, models_doc: dict) -> str:
    lines: list[str] = [HEADER.rstrip("\n"), ""]
    lines += render_limitation_note(docs_claims, classified)
    lines += render_legend()
    lines += render_matrices(rows, inventory, models_doc)
    lines += render_contradictions(rows)
    lines += render_docs_silent(docs_claims)
    lines += render_facets_feed(docs_claims)
    return "\n".join(lines).rstrip("\n") + "\n"


def regenerate(
    docs_claims_path: Path = DOCS_CLAIMS_PATH,
    classified_path: Path = CLASSIFIED_PATH,
    models_path: Path = MODELS_PATH,
    inventory_path: Path = INVENTORY_PATH,
) -> tuple[str, list[dict], dict, dict]:
    docs_claims = load_docs_claims(docs_claims_path)
    classified = load_classified(classified_path)
    models_doc = load_models(models_path)
    inventory = load_inventory(inventory_path)
    rows = build_rows(inventory, models_doc, docs_claims, classified)
    text = render_report(rows, docs_claims, classified, inventory, models_doc)
    return text, rows, docs_claims, classified


def check_generated_drift(
    docs_claims_path: Path = DOCS_CLAIMS_PATH,
    classified_path: Path = CLASSIFIED_PATH,
    models_path: Path = MODELS_PATH,
    inventory_path: Path = INVENTORY_PATH,
) -> tuple[int, int]:
    checks = 0
    problems = 0
    checks += 1
    expected_text, _rows, _dc, _cl = regenerate(docs_claims_path, classified_path, models_path, inventory_path)
    if not OUTPUT_PATH.exists():
        problems += 1
        print(f"FAIL drift: {OUTPUT_PATH} does not exist — run the generator", file=sys.stderr)
    else:
        actual_text = OUTPUT_PATH.read_text()
        if actual_text != expected_text:
            problems += 1
            print(
                f"FAIL drift: {OUTPUT_PATH} does not match a fresh render of its two "
                "inputs — it was hand-edited or is stale (rule 3)",
                file=sys.stderr,
            )
    return checks, problems


def print_summary(rows: list[dict], docs_claims: dict) -> None:
    tally: dict[str, int] = {v: 0 for v in VERDICTS}
    for r in rows:
        tally[r["verdict"]] += 1
    print(f"rows (param x model pairs): {len(rows)}")
    for v in VERDICTS:
        print(f"  {v}: {tally[v]}")
    non_unanimous = sum(1 for r in rows if r["non_unanimous"])
    silent_claims = sum(1 for c in docs_claims["claims"] if c.get("documented_status") == "docs-silent")
    facet_claims = sum(1 for c in docs_claims["claims"] if any(c.get(f) is not None for f in FACET_FIELDS))
    print(f"non-unanimous pairs: {non_unanimous}")
    print(f"docs-silent claims: {silent_claims}")
    print(f"facets awaiting behavioral test: {facet_claims}")


# -----------------------------------------------------------------------------------
# --selftest — embedded fixtures, no external test framework, house style matching
# scripts/build-probe-matrix.py / probes/check-docs-claims.py.
# -----------------------------------------------------------------------------------


def selftest() -> tuple[int, int]:
    problems = 0
    cases = 0

    # --- verdict_for: documented claim + accepted-honored -> docs-corroborated ---
    cases += 1
    v = verdict_for("documented", "accepted-honored")
    if v != "docs-corroborated":
        problems += 1
        print(f"FAIL verdict_for(documented, accepted-honored): expected docs-corroborated, got {v}", file=sys.stderr)

    # --- verdict_for: documented claim + rejected -> docs-contradicted ---
    cases += 1
    v = verdict_for("documented", "rejected")
    if v != "docs-contradicted":
        problems += 1
        print(f"FAIL verdict_for(documented, rejected): expected docs-contradicted, got {v}", file=sys.stderr)

    # --- verdict_for: absent-from-docs claim + rejected -> docs-corroborated — a
    #     documented absence corroborated by a rejection is a positive rule-1b
    #     finding, not an untested cell ---
    cases += 1
    v = verdict_for("absent-from-docs", "rejected")
    if v != "docs-corroborated":
        problems += 1
        print(f"FAIL verdict_for(absent-from-docs, rejected): expected docs-corroborated, got {v}", file=sys.stderr)

    # --- verdict_for: absent-from-docs claim + an accepted state -> docs-contradicted
    #     — an undocumented field the vendor accepted, for all three accepted-family
    #     states ---
    cases += 1
    accepted_results = {
        state: verdict_for("absent-from-docs", state) for state in sorted(ACCEPTED_FAMILY)
    }
    if any(r != "docs-contradicted" for r in accepted_results.values()):
        problems += 1
        print(
            f"FAIL verdict_for(absent-from-docs, <accepted family>): expected "
            f"docs-contradicted for every accepted-family state, got {accepted_results}",
            file=sys.stderr,
        )

    # --- verdict_for: any claim + accepted-unverified -> docs-undecidable ---
    cases += 1
    if verdict_for("documented", "accepted-unverified") != "docs-undecidable" or verdict_for(
        "absent-from-docs", "accepted-unverified"
    ) != "docs-undecidable":
        problems += 1
        print("FAIL verdict_for(*, accepted-unverified): expected docs-undecidable for both claim statuses", file=sys.stderr)

    # --- verdict_for: skipped -> docs-untested; needs-review -> docs-untested ---
    cases += 1
    if verdict_for("documented", "skipped") != "docs-untested":
        problems += 1
        print("FAIL verdict_for(documented, skipped): expected docs-untested", file=sys.stderr)
    cases += 1
    if verdict_for("documented", "needs-review") != "docs-untested":
        problems += 1
        print("FAIL verdict_for(documented, needs-review): expected docs-untested", file=sys.stderr)

    # --- verdict_for: unfired (declared cell, no evidence fired yet) -> docs-untested
    #     — CR-01, a real recurring mid-sweep state classify-probes.py's own STATES
    #     vocabulary includes; must not raise ---
    cases += 1
    if verdict_for("documented", "unfired") != "docs-untested":
        problems += 1
        print("FAIL verdict_for(documented, unfired): expected docs-untested", file=sys.stderr)

    # --- verdict_for: a docs-silent claim renders docs-silent whatever the wire
    #     state — claim status is resolved before wire state ---
    cases += 1
    if verdict_for("docs-silent", "accepted-honored") != "docs-silent" or verdict_for("docs-silent", "rejected") != "docs-silent":
        problems += 1
        print("FAIL verdict_for(docs-silent, *): expected docs-silent regardless of wire state", file=sys.stderr)

    # --- verdict_for: no wire cell at all (wire_state=None) -> docs-untested ---
    cases += 1
    if verdict_for("documented", None) != "docs-untested":
        problems += 1
        print("FAIL verdict_for(documented, None): expected docs-untested for a pair with no wire cell", file=sys.stderr)

    # --- verdict_for: an unrecognized wire state raises rather than returning a
    #     default verdict ---
    cases += 1
    try:
        verdict_for("documented", "not-a-real-state")
        problems += 1
        print("FAIL verdict_for(unrecognized wire state): expected SystemExit, got no exception", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL verdict_for(unrecognized wire state): expected exit 2, got {e.code}", file=sys.stderr)

    # --- verdict_for: an unrecognized documented_status does the same ---
    cases += 1
    try:
        verdict_for("not-a-real-status", "accepted-honored")
        problems += 1
        print("FAIL verdict_for(unrecognized documented_status): expected SystemExit, got no exception", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL verdict_for(unrecognized documented_status): expected exit 2, got {e.code}", file=sys.stderr)

    # --- resolve_pair_verdict: a (param, model) pair with no wire cell at all
    #     renders docs-untested ---
    cases += 1
    verdict, non_unanimous, contributing = resolve_pair_verdict("documented", [])
    if verdict != "docs-untested" or non_unanimous or contributing != []:
        problems += 1
        print(
            f"FAIL resolve_pair_verdict(no cells): expected (docs-untested, False, []), "
            f"got ({verdict}, {non_unanimous}, {contributing})",
            file=sys.stderr,
        )

    # --- resolve_pair_verdict: a pair whose cells carry both rejected and an
    #     accepted state reduces to docs-contradicted and is flagged non-unanimous,
    #     carrying every contributing cell's mode/value/state/probe_id ---
    cases += 1
    mixed_cells = [
        {"param": "p1", "model": "m1", "mode": "default", "value": "v1", "state": "rejected", "probe_id": "px1", "http_status": 400},
        {"param": "p1", "model": "m1", "mode": "thinking-on", "value": "v1", "state": "accepted-honored", "probe_id": "px2", "http_status": 200},
    ]
    verdict, non_unanimous, contributing = resolve_pair_verdict("documented", mixed_cells)
    if verdict != "docs-contradicted" or not non_unanimous or contributing != mixed_cells:
        problems += 1
        print(
            f"FAIL resolve_pair_verdict(mixed): expected (docs-contradicted, True, mixed_cells), "
            f"got ({verdict}, {non_unanimous}, {contributing})",
            file=sys.stderr,
        )

    # --- reduce_verdicts: an empty verdict list fails loud rather than returning a
    #     default ---
    cases += 1
    try:
        reduce_verdicts([])
        problems += 1
        print("FAIL reduce_verdicts([]): expected SystemExit, got no exception", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL reduce_verdicts([]): expected exit 2, got {e.code}", file=sys.stderr)

    # --- glyph_for: five distinct glyphs, one per verdict; an unrecognized verdict
    #     fails loud ---
    cases += 1
    glyphs = {glyph_for(v) for v in VERDICTS}
    if len(glyphs) != 5:
        problems += 1
        print(f"FAIL glyph_for: expected 5 distinct glyphs across VERDICTS, got {glyphs}", file=sys.stderr)
    cases += 1
    try:
        glyph_for("not-a-real-verdict")
        problems += 1
        print("FAIL glyph_for(unrecognized): expected SystemExit, got no exception", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL glyph_for(unrecognized): expected exit 2, got {e.code}", file=sys.stderr)

    # --- anti-overclaiming (D-05): a claim carrying a documented range plus a
    #     single accepted wire cell renders docs-corroborated on the
    #     existence/acceptance facet AND that range appears in the facets section —
    #     the range never appears in the verdict cell and never produces a
    #     corroborated facet in a matrix ---
    range_claim = {
        "param": "p-range",
        "vendor": "v1",
        "documented_status": "documented",
        "documented_name": "p_range",
        "documented_type": "number",
        "documented_range": "0.0 to 2.0",
        "documented_allowed_values": None,
        "documented_default": None,
        "conditionality": None,
        "quote": "ranges from 0.0 to 2.0",
        "source_ref": "src-1",
        "searched_surface": None,
    }
    range_cells = [
        {"param": "p-range", "model": "m1", "mode": "default", "value": "0.7", "state": "accepted-honored", "probe_id": "pr1", "http_status": 200},
    ]
    cases += 1
    verdict, non_unanimous, contributing = resolve_pair_verdict(range_claim["documented_status"], range_cells)
    if verdict != "docs-corroborated":
        problems += 1
        print(
            f"FAIL anti-overclaim: a single-point accepted probe against a "
            f"documented_range claim should verdict docs-corroborated on the "
            f"existence/acceptance facet alone, got {verdict}",
            file=sys.stderr,
        )
    cases += 1
    facets_rendered = "\n".join(render_facets_feed({"claims": [range_claim]}))
    if "0.0 to 2.0" not in facets_rendered:
        problems += 1
        print("FAIL anti-overclaim: documented_range did not appear in the rendered facets section", file=sys.stderr)

    fixture_inventory = {
        "params": [{"id": "p-range", "group": "g1"}],
        "groups": [{"id": "g1", "title": "G1", "order": 10}],
    }
    fixture_models = {"models": [{"slug": "m1", "vendor": "v1"}]}
    fixture_docs_claims = {"checked": "2026-09-01", "claims": [range_claim]}
    fixture_classified = {"checked": "2026-09-01", "evidence_through": "2026-09-01T00:00:00Z", "cells": range_cells}

    cases += 1
    fixture_rows = build_rows(fixture_inventory, fixture_models, fixture_docs_claims, fixture_classified)
    matrix_rendered = "\n".join(render_matrices(fixture_rows, fixture_inventory, fixture_models))
    if "0.0 to 2.0" in matrix_rendered:
        problems += 1
        print("FAIL anti-overclaim: a documented_range value leaked into a rendered matrix cell", file=sys.stderr)

    # --- regenerate(): two consecutive calls on one fixture tree return
    #     byte-identical text; check_generated_drift() reports a finding when the
    #     output file's text differs from a fresh render, and none when it matches ---
    cases += 1
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        docs_claims_path = td_path / "docs-claims.yaml"
        classified_path = td_path / "contract-sweep.yaml"
        models_path = td_path / "models.yaml"
        inventory_path = td_path / "inventory.yaml"
        docs_claims_path.write_text(yaml.safe_dump(fixture_docs_claims, sort_keys=False))
        classified_path.write_text(yaml.safe_dump(fixture_classified, sort_keys=False))
        models_path.write_text(yaml.safe_dump(fixture_models, sort_keys=False))
        inventory_path.write_text(yaml.safe_dump(fixture_inventory, sort_keys=False))

        text1, _rows1, _dc1, _cl1 = regenerate(docs_claims_path, classified_path, models_path, inventory_path)
        text2, _rows2, _dc2, _cl2 = regenerate(docs_claims_path, classified_path, models_path, inventory_path)
        if text1 != text2:
            problems += 1
            print("FAIL regenerate: two consecutive calls on the same fixture tree were not byte-identical", file=sys.stderr)

        cases += 1
        global OUTPUT_PATH
        original_output_path = OUTPUT_PATH
        try:
            OUTPUT_PATH = td_path / "docs-vs-wire.md"
            OUTPUT_PATH.write_text("stale content that does not match a fresh render\n")
            _checks, problems_drift = check_generated_drift(docs_claims_path, classified_path, models_path, inventory_path)
            if problems_drift == 0:
                problems += 1
                print("FAIL check_generated_drift: expected a finding for a stale output file, got 0", file=sys.stderr)

            OUTPUT_PATH.write_text(text1)
            _checks, problems_clean = check_generated_drift(docs_claims_path, classified_path, models_path, inventory_path)
            if problems_clean != 0:
                problems += 1
                print(f"FAIL check_generated_drift: expected 0 findings for a matching output file, got {problems_clean}", file=sys.stderr)
        finally:
            OUTPUT_PATH = original_output_path

    return cases, problems


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="build-docs-vs-wire.py",
        usage="build-docs-vs-wire.py [--check | --selftest]",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        cases, problems = selftest()
        print(f"{cases} cases run, {problems} problem(s)")
        return 1 if problems else 0

    if args.check:
        _checks, problems = check_generated_drift()
        print(f"{problems} problem(s)")
        return 1 if problems else 0

    text, rows, docs_claims, classified = regenerate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)
    print_summary(rows, docs_claims)
    return 0


if __name__ == "__main__":
    sys.exit(main())
