#!/usr/bin/env python3
"""scripts/build-probe-matrix.py — reads probes/classified/contract-sweep.yaml (its
ONLY input, MTX-02's own "from that classified YAML alone" criterion) and writes
comparisons/probes.md — one section per inventory group, a table of parameter rows
against the 12 model columns (both the group order and the model-column order are
derived from the classified YAML's own row order, never a second file).

    python3 scripts/build-probe-matrix.py             # regenerate + print a counted summary
    python3 scripts/build-probe-matrix.py --check      # drift-check against disk
    python3 scripts/build-probe-matrix.py --selftest   # run the embedded fixture battery

Exit codes: 0 clean, 1 problems recorded (--check/--selftest only), 2 bad invocation
or malformed input.

Rule 3 (generated, never hand-edited): a shared header string constant is used by
both the writer and `--check`'s drift comparator, so the two can never independently
drift apart. `checked:`/`evidence_through:` are carried straight from the classified
YAML, never wall-clock — idempotent regeneration is byte-stable.
"""
from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CLASSIFIED_PATH = REPO_ROOT / "probes" / "classified" / "contract-sweep.yaml"
OUTPUT_PATH = REPO_ROOT / "comparisons" / "probes.md"

HEADER = (
    "<!-- GENERATED by scripts/build-probe-matrix.py from\n"
    "     probes/classified/contract-sweep.yaml — do not edit by hand. Regenerate\n"
    "     with `python3 scripts/build-probe-matrix.py`. -->\n"
    "\n"
    "# probes/classified/contract-sweep.yaml, rendered\n"
)

# Glyph legend (MTX-02). Silent acceptance must be visually distinct from a clean
# accept (SWP-02's discipline, conclusion 19's hazard class) — accepted-honored,
# accepted-ignored, silently-translated, and accepted-unverified each get their own
# glyph, never collapsed.
GLYPHS = {
    "rejected": "✗",  # ✗
    "accepted-honored": "✓",  # ✓
    "accepted-ignored": "⚠",  # ⚠ HAZARD
    "silently-translated": "⇄",  # ⇄ HAZARD
    "accepted-unverified": "◐",  # ◐
    "needs-review": "?",
    "skipped": "·",  # ·
    "unfired": "—",  # —
}
OVERRIDE_MARKER = "*"

LEGEND_ROWS = [
    ("✗", "rejected", ""),
    ("✓", "accepted-honored", ""),
    ("⚠", "accepted-ignored", "HAZARD — silent acceptance, no honor signal"),
    ("⇄", "silently-translated", "HAZARD — vendor rewrote the value"),
    ("◐", "accepted-unverified", "accepted, no honor-discriminating signal in this response"),
    ("?", "needs-review", "auto-classification could not resolve a clean verdict"),
    ("·", "skipped", "declared skip (probes/sets/generated/skipped-cells.yaml)"),
    ("—", "unfired", "declared but no evidence yet"),
    ("*", "override applied", "appended to any cell an override touched"),
]


def _fail(code: int, msg: str) -> None:
    """Print a diagnostic and raise SystemExit(code) — the fail-loud path this
    module shares with probes/harness/runner.py and scripts/classify-probes.py."""
    print(msg, file=sys.stderr)
    raise SystemExit(code)


def _load_yaml(path: Path, required_key: str) -> dict:
    try:
        text = Path(path).read_text()
    except OSError as e:
        _fail(2, f"cannot read {path}: {e}")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        _fail(2, f"{path} is not valid YAML: {e}")
    if not isinstance(data, dict) or required_key not in data:
        _fail(2, f"{path}: expected a top-level `{required_key}:` key")
    return data


def load_classified(path: Path = CLASSIFIED_PATH) -> dict:
    return _load_yaml(path, "cells")


def model_column_order(cells: list[dict]) -> list[str]:
    """The 12 model columns, in probes/harness/models.yaml's original row order —
    derived ENTIRELY from the classified YAML's own row order (D-11 guarantees
    every param x model pair is a cell, so every param's cells span all 12
    models; classify-probes.py sorts by (row order, model_order, mode, value), so
    a first-occurrence scan across ALL cells recovers models.yaml's true order
    without reading models.yaml directly — MTX-02's "from that classified YAML
    alone" criterion)."""
    order: list[str] = []
    seen: set[str] = set()
    for c in cells:
        if c["model"] not in seen:
            seen.add(c["model"])
            order.append(c["model"])
    return order


def group_order(cells: list[dict]) -> list[str]:
    """Section order — first-occurrence scan of `group` across the classified
    YAML's own row order. Groups are not contiguous in the underlying registry
    (structural rows appear on both sides of service-tier/reasoning-toggle), so
    this buckets by value rather than assuming contiguity."""
    order: list[str] = []
    seen: set[str] = set()
    for c in cells:
        g = c.get("group")
        if g not in seen:
            seen.add(g)
            order.append(g)
    return order


def glyph_for(cell: dict) -> str:
    state = cell["state"]
    if state not in GLYPHS:
        _fail(2, f"glyph_for: state {state!r} is outside the rendered glyph vocabulary {sorted(GLYPHS)}")
    glyph = GLYPHS[state]
    if cell.get("override") is not None:
        glyph += OVERRIDE_MARKER
    return glyph


def resolve_cell(
    *,
    param: str,
    model: str,
    mode,
    value,
    exact_index: dict,
    skip_by_mode_index: dict,
    skip_universal_index: dict,
    model_mode_index: dict | None = None,
) -> dict:
    """One (param, model) pair may carry several cells (one per mode/value the
    row's axis expands to) or exactly one skip cell that applies regardless of
    mode/value (a pair-level `no-request-field-for-vendor`/`wire-shape-incompatible`
    skip never carries a mode or value of its own). Lookup, in order:
    1. An exact (param, model, mode, value) match — a real fired/unfired cell.
       Skipped entirely when `value is None` (see tier 4 below).
    2. A skip recorded at the SAME mode (a per-mode toggle skip, e.g.
       `no-thinking-off-toggle` at mode `thinking-off`) — skip cells never carry a
       value, so this tier ignores `value`.
    3. A universal (pair-level, mode `n/a`) skip — applies to every mode/value row
       for this param, since the model never fires this parameter at all.
    4. (2026-09-01, Phase 11 plan 11-04, D-09 "fix-before-fire") When `value is
       None` — row_keys_for_param()'s PER-MODEL-DIVERGENT sentinel, emitted only
       when a param's models genuinely fired different values at the same mode
       (not a shared boundary-contract value set) — resolve this model's own
       single cell for (param, mode) directly from `model_mode_index`, ignoring
       the now-meaningless shared value dimension. More than one candidate here
       is an ambiguity this fallback cannot resolve and fails loud, same as an
       unresolvable pair.
    D-11 guarantees every (param, model) pair resolves at one of these tiers —
    a resolution failure is a structural registry/generator defect, not a
    renderable state, so it fails loud rather than rendering a guessed glyph."""
    if value is not None:
        cell = exact_index.get((param, model, mode, value))
        if cell is not None:
            return cell
    cell = skip_by_mode_index.get((param, model, mode))
    if cell is not None:
        return cell
    cell = skip_universal_index.get((param, model))
    if cell is not None:
        return cell
    if value is None:
        candidates = (model_mode_index or {}).get((param, model, mode)) or []
        if len(candidates) == 1:
            return candidates[0]
        if len(candidates) > 1:
            _fail(
                2,
                f"resolve_cell: per-model-divergent fallback is ambiguous for "
                f"param={param!r} model={model!r} mode={mode!r} — {len(candidates)} "
                "candidate cells, expected exactly 1",
            )
    _fail(
        2,
        f"resolve_cell: no cell resolves for param={param!r} model={model!r} mode={mode!r} "
        f"value={value!r} — every (param, model) pair must be an emitted, unfired, or "
        "declared-skip cell (D-11); this is a structural registry/classifier defect",
    )


def build_indexes(cells: list[dict]) -> tuple[dict, dict, dict, dict]:
    exact_index: dict = {}
    skip_by_mode_index: dict = {}
    skip_universal_index: dict = {}
    model_mode_index: dict = defaultdict(list)   # (param, model, mode) -> [cell, ...]
    # (plan 11-04) the resolve_cell() tier-4 fallback for a per-model-divergent
    # row (see row_keys_for_param()) — never consulted for any pre-existing row,
    # where the tier-1 exact match always succeeds.
    for c in cells:
        key = (c["param"], c["model"], c["mode"], c["value"])
        exact_index[key] = c
        model_mode_index[(c["param"], c["model"], c["mode"])].append(c)
        if c["state"] == "skipped":
            skip_by_mode_index[(c["param"], c["model"], c["mode"])] = c
            if c["mode"] in (None, "n/a"):
                skip_universal_index[(c["param"], c["model"])] = c
    return exact_index, skip_by_mode_index, skip_universal_index, dict(model_mode_index)


def row_keys_for_param(cells_for_param: list[dict]) -> list[tuple]:
    """The distinct (mode, value) row keys a param renders as — every NON-skipped
    cell's (mode, value) pair, deduplicated, in first-occurrence order (which is
    already the classified YAML's own declared order: mode/value ascending within
    the param). A param whose every cell is a skip (should not happen per D-11 —
    every swept row fires at least one model) falls back to its skip cells' own
    (mode, value) pairs so the row is still rendered rather than silently dropped.

    PER-MODEL-DIVERGENT modes (2026-09-01, Phase 11 plan 11-04, D-09
    "fix-before-fire"): every row before this one shared ONE value (or a
    boundary-contract row's small shared value SET, D-03) identically across
    every firing model at a mode — each value's own model-set equals the
    FULL set of models firing this (param, mode), so the (mode, value) key
    was safe to treat as global. The calibration batch broke that invariant
    for `anthropic-thinking-object`: 3 of Anthropic's 4 models moved to a
    genuinely different probe value than the 4th, at the same mode
    (`default`) — the "adaptive" value's model-set (3 models) is a PROPER
    SUBSET of the mode's full model-set (4 models), not the whole thing, and
    likewise for the 4th model's own value. Detected generically: at a given
    mode, if ANY value's model-set is not equal to the union of every
    model-set at that mode (i.e. not every firing model fired every declared
    value), the mode is divergent — this correctly leaves a real
    boundary-contract row (every value fired at every model, so each
    value's model-set trivially equals the full union) on the ordinary
    per-value path unchanged, whether the values are shared by all models
    (boundary contract) or, degenerate case, each model has its own entirely
    unique value (len(models)==1 for every value, also a subset unless there
    is only one model total). Such a mode's row key becomes `(mode, None)` —
    a sentinel resolve_cell() reads to resolve each model's own cell
    directly (its model_mode_index tier), rather than a nominal shared value
    that would only be true for SOME of the row's models."""
    values_by_mode: dict = defaultdict(lambda: defaultdict(set))
    for c in cells_for_param:
        if c["state"] == "skipped":
            continue
        values_by_mode[c["mode"]][c["value"]].add(c["model"])
    divergent_modes = set()
    for mode, models_by_value in values_by_mode.items():
        if len(models_by_value) <= 1:
            continue
        all_models_at_mode = set().union(*models_by_value.values())
        if any(models != all_models_at_mode for models in models_by_value.values()):
            divergent_modes.add(mode)

    keys: list[tuple] = []
    seen: set[tuple] = set()
    for c in cells_for_param:
        if c["state"] == "skipped":
            continue
        key = (c["mode"], None) if c["mode"] in divergent_modes else (c["mode"], c["value"])
        if key not in seen:
            seen.add(key)
            keys.append(key)
    if not keys:
        for c in cells_for_param:
            key = (c["mode"], c["value"])
            if key not in seen:
                seen.add(key)
                keys.append(key)
    return keys


def hazard_listing_rows(cells: list[dict]) -> list[dict]:
    """Every hazard-bearing cell (SWP-02: `hazard` is non-null — states
    accepted-ignored/silently-translated), in the classified YAML's own declared
    order (never re-sorted) — the plain-language section listing them by
    parameter, model and probe_id that this repo's own human legibility check
    (this plan's <verify> § Human check) reads alongside the glyph table."""
    return [c for c in cells if c.get("hazard")]


def render_matrix(classified: dict) -> str:
    cells = classified["cells"]
    checked = classified.get("checked")
    evidence_through = classified.get("evidence_through")

    models = model_column_order(cells)
    groups = group_order(cells)
    exact_index, skip_by_mode_index, skip_universal_index, model_mode_index = build_indexes(cells)

    by_param: dict[str, list[dict]] = defaultdict(list)
    param_group: dict[str, str] = {}
    param_order: list[str] = []
    for c in cells:
        p = c["param"]
        if p not in param_group:
            param_group[p] = c.get("group")
            param_order.append(p)
        by_param[p].append(c)

    lines: list[str] = [HEADER.rstrip("\n"), ""]
    lines.append(f"`checked:` {checked}  ")
    lines.append(f"`evidence_through:` {evidence_through}")
    lines.append("")
    lines.append("## Legend")
    lines.append("")
    lines.append("| Glyph | State | Note |")
    lines.append("|---|---|---|")
    for glyph, state, note in LEGEND_ROWS:
        lines.append(f"| {glyph} | {state} | {note} |")
    lines.append("")

    for group in groups:
        params_in_group = [p for p in param_order if param_group[p] == group]
        if not params_in_group:
            continue
        lines.append(f"## {group}")
        lines.append("")
        header_cols = ["Parameter"] + models
        lines.append("| " + " | ".join(header_cols) + " |")
        lines.append("|" + "---|" * len(header_cols))
        for param in params_in_group:
            row_keys = row_keys_for_param(by_param[param])
            multi = len(row_keys) > 1
            for mode, value in row_keys:
                label = param
                if multi:
                    # value is None for a per-model-divergent row (plan
                    # 11-04) — no single value is true for the whole row, so
                    # the label says so plainly instead of printing "None".
                    shown_value = "varies by model" if value is None else value
                    label = f"{param} (mode={mode}, value={shown_value})"
                row_cells = [label]
                for model in models:
                    cell = resolve_cell(
                        param=param,
                        model=model,
                        mode=mode,
                        value=value,
                        exact_index=exact_index,
                        skip_by_mode_index=skip_by_mode_index,
                        skip_universal_index=skip_universal_index,
                        model_mode_index=model_mode_index,
                    )
                    row_cells.append(glyph_for(cell))
                lines.append("| " + " | ".join(row_cells) + " |")
        lines.append("")

    # SWP-02: every hazard-bearing cell listed explicitly, plainly, by name — a
    # reader must be able to find every silent-acceptance instance without
    # cross-referencing the classified YAML alongside this file.
    hazards = hazard_listing_rows(cells)
    lines.append("## Hazards")
    lines.append("")
    lines.append(
        "Every cell whose state is ⚠ `accepted-ignored` or ⇄ `silently-translated` — "
        "the silent-acceptance hazard class SWP-02 requires stay visually and "
        "structurally distinct from a clean accept (conclusion 19, docs/conclusions.md)."
    )
    lines.append("")
    if hazards:
        lines.append("| Parameter | Model | State | probe_id | Hazard |")
        lines.append("|---|---|---|---|---|")
        for c in hazards:
            lines.append(
                f"| {c['param']} | {c['model']} | {glyph_for(c)} {c['state']} | "
                f"{c.get('probe_id') or '—'} | {c['hazard']} |"
            )
    else:
        lines.append("None yet — no cell has classified as `accepted-ignored` or `silently-translated`.")
    lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def regenerate(path: Path = CLASSIFIED_PATH) -> tuple[str, dict]:
    classified = load_classified(path)
    text = render_matrix(classified)
    return text, classified


def check_generated_drift(path: Path = CLASSIFIED_PATH) -> tuple[int, int]:
    checks = 0
    problems = 0
    checks += 1
    expected_text, _classified = regenerate(path)
    if not OUTPUT_PATH.exists():
        problems += 1
        print(f"FAIL drift: {OUTPUT_PATH} does not exist — run the generator", file=sys.stderr)
    else:
        actual_text = OUTPUT_PATH.read_text()
        if actual_text != expected_text:
            problems += 1
            print(
                f"FAIL drift: {OUTPUT_PATH} does not match a fresh render of {CLASSIFIED_PATH} "
                "— it was hand-edited or is stale (rule 3)",
                file=sys.stderr,
            )
    return checks, problems


def print_summary(classified: dict) -> None:
    cells = classified["cells"]
    tally: dict[str, int] = {}
    for c in cells:
        tally[c["state"]] = tally.get(c["state"], 0) + 1
    print(f"cells read: {len(cells)}")
    print(f"model columns: {len(model_column_order(cells))}")
    print(f"groups (sections): {len(group_order(cells))}")
    for state in sorted(tally):
        print(f"  {state}: {tally[state]}")


# -----------------------------------------------------------------------------------
# --selftest — embedded fixtures, no external test framework, house style matching
# probes/inventory-to-sets.py / scripts/classify-probes.py.
# -----------------------------------------------------------------------------------


def selftest() -> tuple[int, int]:
    problems = 0
    cases = 0

    fixture_cells = [
        {"param": "p1", "group": "g1", "model": "m1", "mode": "default", "value": "v1", "state": "rejected",
         "probe_id": "x", "override": None},
        {"param": "p1", "group": "g1", "model": "m2", "mode": "n/a", "value": None, "state": "skipped",
         "probe_id": None, "override": None},
        {"param": "p2", "group": "g2", "model": "m1", "mode": "thinking-off", "value": None, "state": "skipped",
         "probe_id": None, "override": None},
        {"param": "p2", "group": "g2", "model": "m1", "mode": "thinking-on", "value": "v2", "state": "accepted-unverified",
         "probe_id": "y", "override": None},
        {"param": "p2", "group": "g2", "model": "m2", "mode": "thinking-off", "value": None, "state": "skipped",
         "probe_id": None, "override": None},
        {"param": "p2", "group": "g2", "model": "m2", "mode": "thinking-on", "value": "v2", "state": "unfired",
         "probe_id": None, "override": None},
    ]

    # --- model_column_order: first-occurrence order across ALL cells ---
    cases += 1
    order = model_column_order(fixture_cells)
    if order != ["m1", "m2"]:
        problems += 1
        print(f"FAIL model_column_order: expected ['m1', 'm2'], got {order}", file=sys.stderr)

    # --- group_order: first-occurrence, deduplicated, no dependence on contiguity ---
    cases += 1
    fixture_noncontig = fixture_cells + [{"param": "p3", "group": "g1", "model": "m1", "mode": "default", "value": "v3", "state": "rejected", "probe_id": "z", "override": None}]
    g_order = group_order(fixture_noncontig)
    if g_order != ["g1", "g2"]:
        problems += 1
        print(f"FAIL group_order: expected ['g1', 'g2'], got {g_order}", file=sys.stderr)

    # --- glyph_for: distinct glyphs for the four accepted/hazard states ---
    cases += 1
    glyphs = {
        glyph_for({"state": "accepted-honored", "override": None}),
        glyph_for({"state": "accepted-ignored", "override": None}),
        glyph_for({"state": "silently-translated", "override": None}),
        glyph_for({"state": "accepted-unverified", "override": None}),
    }
    if len(glyphs) != 4:
        problems += 1
        print(f"FAIL glyph_for: expected 4 distinct glyphs, got {glyphs}", file=sys.stderr)

    # --- glyph_for: override marker appended ---
    cases += 1
    plain = glyph_for({"state": "rejected", "override": None})
    overridden = glyph_for({"state": "rejected", "override": {"date": "2026-09-01", "reason": "fixture"}})
    if overridden != plain + OVERRIDE_MARKER:
        problems += 1
        print(f"FAIL glyph_for(override): expected {plain + OVERRIDE_MARKER!r}, got {overridden!r}", file=sys.stderr)

    # --- glyph_for: an unrecognized state fails loud rather than rendering blank ---
    cases += 1
    try:
        glyph_for({"state": "not-a-real-state", "override": None})
        problems += 1
        print("FAIL glyph_for(unknown state): expected SystemExit(2), got no exception", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL glyph_for(unknown state): expected exit 2, got {e.code}", file=sys.stderr)

    # --- resolve_cell: three-tier lookup — exact, per-mode skip, universal skip ---
    cases += 1
    exact_index, skip_by_mode_index, skip_universal_index, model_mode_index = build_indexes(fixture_cells)
    exact_hit = resolve_cell(
        param="p2", model="m1", mode="thinking-on", value="v2",
        exact_index=exact_index, skip_by_mode_index=skip_by_mode_index, skip_universal_index=skip_universal_index,
        model_mode_index=model_mode_index,
    )
    if exact_hit["state"] != "accepted-unverified":
        problems += 1
        print(f"FAIL resolve_cell(exact): expected accepted-unverified, got {exact_hit['state']}", file=sys.stderr)
    per_mode_hit = resolve_cell(
        param="p2", model="m1", mode="thinking-off", value="v2",
        exact_index=exact_index, skip_by_mode_index=skip_by_mode_index, skip_universal_index=skip_universal_index,
    )
    if per_mode_hit["state"] != "skipped":
        problems += 1
        print(f"FAIL resolve_cell(per-mode skip): expected skipped, got {per_mode_hit['state']}", file=sys.stderr)
    universal_hit = resolve_cell(
        param="p1", model="m2", mode="default", value="v1",
        exact_index=exact_index, skip_by_mode_index=skip_by_mode_index, skip_universal_index=skip_universal_index,
    )
    if universal_hit["state"] != "skipped":
        problems += 1
        print(f"FAIL resolve_cell(universal skip): expected skipped, got {universal_hit['state']}", file=sys.stderr)

    # --- resolve_cell: a genuinely unresolvable pair fails loud (exit 2) ---
    cases += 1
    try:
        resolve_cell(
            param="p-nonexistent", model="m-nonexistent", mode="default", value="v1",
            exact_index=exact_index, skip_by_mode_index=skip_by_mode_index, skip_universal_index=skip_universal_index,
        )
        problems += 1
        print("FAIL resolve_cell(unresolvable): expected SystemExit(2), got no exception", file=sys.stderr)
    except SystemExit as e:
        if e.code != 2:
            problems += 1
            print(f"FAIL resolve_cell(unresolvable): expected exit 2, got {e.code}", file=sys.stderr)

    # --- row_keys_for_param: distinct non-skip (mode, value) pairs, deduplicated ---
    cases += 1
    keys = row_keys_for_param(by_param_fixture := [c for c in fixture_cells if c["param"] == "p2"])
    if keys != [("thinking-on", "v2")]:
        problems += 1
        print(f"FAIL row_keys_for_param: expected [('thinking-on', 'v2')], got {keys}", file=sys.stderr)

    # --- row_keys_for_param / resolve_cell: PER-MODEL-DIVERGENT row (plan
    #     11-04, D-09 "fix-before-fire") — two models each fire a DIFFERENT
    #     value at the same mode (no shared value, unlike a boundary-contract
    #     row where every value fires at every model). row_keys_for_param()
    #     must collapse this to a single (mode, None) sentinel row, and
    #     resolve_cell() must resolve EACH model's own cell via the
    #     model_mode_index fallback rather than failing loud. ---
    cases += 1
    divergent_cells = [
        {"param": "p-div", "group": "g1", "model": "m1", "mode": "default", "value": "va",
         "state": "unfired", "probe_id": None, "override": None},
        {"param": "p-div", "group": "g1", "model": "m2", "mode": "default", "value": "vb",
         "state": "rejected", "probe_id": "z", "override": None},
    ]
    divergent_keys = row_keys_for_param(divergent_cells)
    if divergent_keys != [("default", None)]:
        problems += 1
        print(f"FAIL row_keys_for_param(divergent): expected [('default', None)], got {divergent_keys}", file=sys.stderr)
    div_exact, div_skip_mode, div_skip_universal, div_model_mode = build_indexes(divergent_cells)
    div_hit_m1 = resolve_cell(
        param="p-div", model="m1", mode="default", value=None,
        exact_index=div_exact, skip_by_mode_index=div_skip_mode, skip_universal_index=div_skip_universal,
        model_mode_index=div_model_mode,
    )
    div_hit_m2 = resolve_cell(
        param="p-div", model="m2", mode="default", value=None,
        exact_index=div_exact, skip_by_mode_index=div_skip_mode, skip_universal_index=div_skip_universal,
        model_mode_index=div_model_mode,
    )
    if div_hit_m1["state"] != "unfired" or div_hit_m2["state"] != "rejected":
        problems += 1
        print(
            f"FAIL resolve_cell(divergent): expected (unfired, rejected), got "
            f"({div_hit_m1['state']}, {div_hit_m2['state']})",
            file=sys.stderr,
        )

    # --- render_matrix: deterministic, byte-identical for identical input ---
    cases += 1
    fixture_doc = {"checked": "2026-09-01", "evidence_through": None, "cells": fixture_cells}
    first = render_matrix(fixture_doc)
    second = render_matrix(fixture_doc)
    if first != second:
        problems += 1
        print("FAIL render_matrix: expected byte-identical output for identical input", file=sys.stderr)

    # --- render_matrix: legend contains all four accepted/hazard glyphs, and both
    #     HAZARD states are named as such ---
    cases += 1
    rendered = render_matrix(fixture_doc)
    if rendered.count("HAZARD") != 2:
        problems += 1
        print(f"FAIL render_matrix: expected exactly 2 'HAZARD' mentions in the legend, got {rendered.count('HAZARD')}", file=sys.stderr)

    # --- hazard_listing_rows: only hazard-bearing cells (non-null `hazard`),
    #     never re-sorted from the classified YAML's own declared order (SWP-02) ---
    cases += 1
    hazard_fixture_cells = [
        {"param": "p1", "group": "g1", "model": "m1", "mode": "default", "value": "v1", "state": "accepted-ignored",
         "probe_id": "haz1", "hazard": "silent acceptance text", "override": None},
        {"param": "p1", "group": "g1", "model": "m2", "mode": "default", "value": "v1", "state": "accepted-honored",
         "probe_id": "clean1", "hazard": None, "override": None},
        {"param": "p2", "group": "g1", "model": "m1", "mode": "default", "value": "v2", "state": "silently-translated",
         "probe_id": "haz2", "hazard": "translated text", "override": None},
        {"param": "p2", "group": "g1", "model": "m2", "mode": "default", "value": "v2", "state": "accepted-honored",
         "probe_id": "clean2", "hazard": None, "override": None},
    ]
    haz_rows = hazard_listing_rows(hazard_fixture_cells)
    if [c["probe_id"] for c in haz_rows] != ["haz1", "haz2"]:
        problems += 1
        print(f"FAIL hazard_listing_rows: expected [haz1, haz2] in declared order, got {[c.get('probe_id') for c in haz_rows]}", file=sys.stderr)

    # --- render_matrix: the ## Hazards section lists every hazard-bearing cell's
    #     probe_id and omits the clean accept — a reader must be able to find it
    #     without opening the classified YAML alongside this file ---
    cases += 1
    haz_doc = {"checked": "2026-09-01", "evidence_through": None, "cells": hazard_fixture_cells}
    haz_rendered = render_matrix(haz_doc)
    if "## Hazards" not in haz_rendered or "haz1" not in haz_rendered or "haz2" not in haz_rendered:
        problems += 1
        print("FAIL render_matrix: ## Hazards section missing or missing a hazard-bearing probe_id", file=sys.stderr)
    if "clean1" in haz_rendered.split("## Hazards")[1]:
        problems += 1
        print("FAIL render_matrix: a clean accept (accepted-honored) leaked into the ## Hazards section", file=sys.stderr)

    # --- render_matrix: a classified doc with NO hazard-bearing cells renders an
    #     explicit "None" line, never an empty/missing section ---
    cases += 1
    clean_rendered = render_matrix(fixture_doc)
    if "## Hazards" not in clean_rendered or "None yet" not in clean_rendered:
        problems += 1
        print("FAIL render_matrix: expected an explicit 'None' Hazards section for a hazard-free doc", file=sys.stderr)

    return cases, problems


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="build-probe-matrix.py",
        usage="build-probe-matrix.py [--check | --selftest]",
    )
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        cases, problems = selftest()
        print(f"{cases} cases run, {problems} problem(s)")
        return 1 if problems else 0

    if args.check:
        checks, problems = check_generated_drift()
        print(f"{problems} problem(s)")
        return 1 if problems else 0

    text, classified = regenerate()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(text)
    print_summary(classified)
    return 0


if __name__ == "__main__":
    sys.exit(main())
