#!/usr/bin/env python3
"""Generate comparisons/tools.md from the YAML frontmatter of every tool report.

The index is generated, never hand-edited: a hand-kept index drifts from the
reports it describes, and you find out when it's already wrong.

    python3 scripts/build-tool-index.py            # write the index
    python3 scripts/build-tool-index.py --check    # verify frontmatter, write nothing

--check also asserts each report's pinned `commit` still matches the clone's HEAD.
A stale SHA silently invalidates every architecture claim in the document.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
NOTES = ROOT / "notes"
OUT = ROOT / "comparisons" / "tools.md"
FEATURES_OUT = ROOT / "comparisons" / "features.md"

# Fixed vocabulary — order defines the matrix columns. Keep small and axis-aligned;
# vendor pet names don't get columns.
FEATURE_KEYS = [
    "mcp", "lsp", "hooks", "skills", "subagents", "plan_mode",
    "rules_files", "model_agnostic", "session_sharing", "evals",
]

REQUIRED = ("name", "layer", "depth")
DEPTH_ORDER = {"deep-dive": 0, "survey": 1, "stub": 2}
LAYER_NAMES = {
    1: "Models",
    2: "Harnesses",
    3: "Capability extensions",
    4: "Workflow frameworks",
    5: "Execution environments",
}


def read_frontmatter(path: Path) -> dict | None:
    """Return the YAML frontmatter of a markdown file, or None if it has none."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    data = yaml.safe_load(text[4:end])
    return data if isinstance(data, dict) else None


def collect() -> list[dict]:
    reports = []
    for path in sorted(NOTES.rglob("*.md")):
        if path.name.startswith("_") or path.name == "index.md":
            continue  # templates and layer indexes are not reports
        fm = read_frontmatter(path)
        if fm is None:
            continue
        missing = [k for k in REQUIRED if k not in fm]
        if missing:
            print(f"warn: {path.relative_to(ROOT)} missing {missing}", file=sys.stderr)
            continue
        fm["_path"] = path
        reports.append(fm)
    return sorted(
        reports,
        key=lambda r: (r["layer"], DEPTH_ORDER.get(r["depth"], 9), r["name"]),
    )


def check(reports: list[dict]) -> int:
    """Assert every pinned commit still matches the clone's HEAD."""
    problems = 0
    for r in reports:
        pinned = r.get("commit")
        if not pinned or not r.get("open_source", True):
            continue
        clone = ROOT / "upstream" / r["name"]
        if not (clone / ".git").is_dir():
            print(f"warn: {r['name']} pinned to {pinned} but not cloned", file=sys.stderr)
            continue
        head = subprocess.run(
            ["git", "-C", str(clone), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        if not head.startswith(str(pinned)) and not str(pinned).startswith(head):
            print(
                f"STALE: {r['name']} report pins {pinned}, clone HEAD is {head} "
                f"— re-read or re-pin before trusting {r['_path'].relative_to(ROOT)}",
                file=sys.stderr,
            )
            problems += 1
    return problems


def render(reports: list[dict]) -> str:
    date = max((str(r.get("read_at", "")) for r in reports), default="")
    lines = [
        "# Tool index",
        "",
        "<!-- GENERATED by scripts/build-tool-index.py — do not edit by hand. -->",
        "<!-- Edit the frontmatter of the reports in notes/, then re-run the script. -->",
        "",
        f"Every tool with a report, flattened across layers for comparison. Newest read: `{date}`.",
        "",
        "`depth` is the honesty column: **stub** means facts were collected mechanically but "
        "nobody read the source; **survey** means it was used or skimmed; **deep-dive** means "
        "the agent loop and context assembly were actually traced.",
        "",
        "| Layer | Tool | Surfaces · exec | Stack | License | Version read | Depth | Report |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in reports:
        stack = r.get("stack") or []
        stack = ", ".join(stack) if isinstance(stack, list) else str(stack)
        rel = r["_path"].relative_to(ROOT)
        link = f"[{r['name']}](../{rel})"
        version = r.get("version") or "—"
        if not r.get("open_source", True):
            version = "closed source"
        surfaces = r.get("surfaces") or []
        if surfaces:
            shape = " + ".join(surfaces)
            if r.get("execution"):
                shape += f" · {r['execution']}"
        else:
            shape = "—"
        lines.append(
            f"| {r['layer']} · {LAYER_NAMES.get(r['layer'], '?')} | {r['name']} | {shape} | "
            f"{stack or '—'} | {r.get('license') or '—'} | `{version}` | "
            f"{r['depth']} | {link} |"
        )

    counts = {}
    for r in reports:
        counts[r["depth"]] = counts.get(r["depth"], 0) + 1
    summary = " · ".join(f"{v} {k}" for k, v in sorted(counts.items()))
    lines += ["", f"**{len(reports)} tools** — {summary}.", ""]
    return "\n".join(lines)


def render_features(reports: list[dict]) -> str:
    lines = [
        "# Feature matrix",
        "",
        "<!-- GENERATED by scripts/build-tool-index.py — do not edit by hand. -->",
        "<!-- Edit the `features:` frontmatter of the reports in notes/, then re-run. -->",
        "",
        "Cells: **✓** verified present · **✗** verified absent · **·** not yet checked.",
        "The dot is load-bearing — it is *not* a no. A feature key is only set in a",
        "report's frontmatter when confirmed in source or official docs.",
        "",
        "| Tool | " + " | ".join(k.replace("_", " ") for k in FEATURE_KEYS) + " |",
        "|---|" + "---|" * len(FEATURE_KEYS),
    ]
    unknown_keys: set[str] = set()
    for r in reports:
        feats = r.get("features") or {}
        if not isinstance(feats, dict):
            feats = {}
        unknown_keys.update(k for k in feats if k not in FEATURE_KEYS)
        cells = []
        for key in FEATURE_KEYS:
            v = feats.get(key)
            if v is True:
                cells.append("✓")
            elif v is False:
                cells.append("✗")
            elif isinstance(v, list):
                cells.append(", ".join(f"`{x}`" for x in v))
            elif v is None:
                cells.append("·")
            else:
                cells.append(f"`{v}`")
        rel = r["_path"].relative_to(ROOT)
        lines.append(f"| [{r['name']}](../{rel}) | " + " | ".join(cells) + " |")
    for k in sorted(unknown_keys):
        print(f"warn: feature key '{k}' not in FEATURE_KEYS — not rendered", file=sys.stderr)
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    reports = collect()
    if not reports:
        print("no reports with frontmatter found", file=sys.stderr)
        return 1

    if "--check" in sys.argv:
        problems = check(reports)
        print(f"{len(reports)} reports checked, {problems} stale")
        return 1 if problems else 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(reports), encoding="utf-8")
    FEATURES_OUT.write_text(render_features(reports), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(reports)} tools")
    print(f"wrote {FEATURES_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
