#!/usr/bin/env python3
"""Fail-hard lint for this repo's taxonomy vocabulary — reads taxonomy.yaml as the sole
source of truth and flags drift in current-state documents, extending the fail-hard
rule-3/rule-4 pattern the other two `--check` generators already enforce (methodology.md):
a hand-kept vocabulary drifts from what the ADRs actually decided, and you find out when
it's already wrong; a claim about which term is canonical is only as good as the check
that verifies it against the decision record.

    python3 scripts/check-taxonomy.py              # run the check (default)
    python3 scripts/check-taxonomy.py --check       # identical to the bare invocation
    python3 scripts/check-taxonomy.py --selftest    # run the embedded fixtures instead

Exit codes: 0 clean, 1 violations found (or a fixture that failed to discriminate),
2 unknown argument.

This script checks; it writes nothing into the repo under any invocation (D-07 — the
honest name).

The lint is EXPECTED to exit non-zero against the real repo as of Phase 2 — the red
findings are Phase 3's work queue, not a bug here. Only --selftest must be green at the
end of this phase (LINT-07, partial).
"""
from __future__ import annotations

import fnmatch
import re
import shutil
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TAXONOMY = ROOT / "taxonomy.yaml"

# A file containing this marker is generated output (comparisons/*.md, refs/index.md)
# and is never a lint target directly — its generator owns the vocabulary it emits
# (methodology rule 3). This is a backstop: exempt_paths.skip_entirely already lists
# comparisons/*, so this catches a newly generated file before anyone remembers to add
# its path there.
GENERATED_MARKER = "GENERATED by scripts/"

FRONTMATTER_KEY_RE = re.compile(r"^(\s*[A-Za-z0-9_.\-]+:)\s?")


def load_taxonomy(path: Path = TAXONOMY) -> dict:
    """Read taxonomy.yaml with the safe loader (matches both existing generators).

    Nothing the lint validates against may be hardcoded in this script: terms,
    deny-lists, compounds, and path patterns all come from this file (VOCAB-02).
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        sys.exit(f"cannot read {path}: {e}")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        sys.exit(f"{path} is not valid YAML: {e}")
    if not isinstance(data, dict):
        sys.exit(f"{path} did not parse to a mapping")
    return data


def read_frontmatter(path: Path) -> dict | None:
    """Return the YAML frontmatter of a markdown file, or None if it has none.

    Duplicated verbatim from build-refs-index.py rather than imported: ten lines, and
    this script validates a different schema — coupling would mean one script's
    vocabulary change breaking another (same rationale as build-refs-index.py's own
    copy of this function).
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    data = yaml.safe_load(text[4:end])
    return data if isinstance(data, dict) else None


def is_exempt(rel: str, taxo: dict) -> str | None:
    """Return the exempt_paths pattern matching `rel`, or None if it is a lint target.

    Only skip_entirely and append_only make a file invisible to the walk; body_exempt
    and adr_title_exempt are per-line exemptions applied inside check(), not here.
    """
    exempt = taxo.get("exempt_paths", {}) or {}
    patterns = (exempt.get("skip_entirely", []) or []) + (exempt.get("append_only", []) or [])
    for pat in patterns:
        if fnmatch.fnmatch(rel, pat):
            return pat
    return None


def walk(taxo: dict, root: Path = ROOT):
    """Yield every current-state markdown file under `root`: not exempt, not generated."""
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).as_posix()
        if is_exempt(rel, taxo):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if GENERATED_MARKER in text:
            continue
        yield path


def split_frontmatter(text: str) -> tuple[list[tuple[int, str]], list[tuple[int, str]]]:
    """Split a file's text into (frontmatter_lines, body_lines), each a list of
    (1-indexed line number, scannable text).

    The prose scanner reads BODY lines as-is, plus frontmatter lines with their leading
    `key:` token stripped — a frontmatter key is schema (governed by schema_renames,
    Plan 02), not prose, so `layer: 4` must not flag every report while the key rename
    is still pending (dormancy contract). A frontmatter *value* or trailing comment is
    prose and stays in scope, hence the strip-not-drop.
    """
    lines = text.splitlines()
    frontmatter_lines: list[tuple[int, str]] = []
    body_start = 0
    if lines and lines[0] == "---":
        end = None
        for i in range(1, len(lines)):
            if lines[i] == "---":
                end = i
                break
        if end is not None:
            for i in range(1, end):
                stripped = FRONTMATTER_KEY_RE.sub("", lines[i], count=1)
                frontmatter_lines.append((i + 1, stripped))
            body_start = end + 1
    body_lines = [(i + 1, lines[i]) for i in range(body_start, len(lines))]
    return frontmatter_lines, body_lines


def _deny_index(taxo: dict) -> tuple[re.Pattern | None, dict, list[str]]:
    """Build (and cache on `taxo`) the single alternation regex over every deny-listed
    term, longest-first so a matched compound like "cross-layer" reports as itself
    rather than also as "layer" — `\\b` on the whole alternative plus finditer's
    non-overlapping scan means the embedded "layer" is never independently re-tried
    once "cross-layer" has consumed that span.
    """
    cached = taxo.get("_deny_index")
    if cached is not None:
        return cached
    entries: list[tuple[str, dict]] = []
    seen: set[str] = set()
    for term in taxo.get("terms", []) or []:
        for d in term.get("deny_list", []) or []:
            if d.endswith(":"):
                # Frontmatter-key entries (e.g. "kind:") are schema, not prose — Plan
                # 02's schema-rename check owns these. Known false positive this
                # exclusion prevents: notes/05-capability-extensions/ai-memory.md:90
                # ("Table stakes in the kind: store + retrieve + MCP.") — ordinary
                # prose, not the report frontmatter key.
                continue
            key = d.lower()
            if key in seen:
                continue
            seen.add(key)
            entries.append((d, term))
    entries.sort(key=lambda e: -len(e[0]))
    pattern = None
    if entries:
        alt = "|".join(re.escape(d) for d, _ in entries)
        pattern = re.compile(rf"\b({alt})\b", re.IGNORECASE)
    lookup = {d.lower(): term for d, term in entries}
    compounds = [
        c["compound"]
        for term in taxo.get("terms", []) or []
        for c in term.get("deny_list_exempt_compounds", []) or []
    ]
    result = (pattern, lookup, compounds)
    taxo["_deny_index"] = result
    return result


def deny_matches(line_text: str, taxo: dict) -> list[tuple[int, int, str, dict | None]]:
    """Find deny-listed terms in one line of prose.

    Skips a match falling inside any deny_list_exempt_compounds[].compound phrase
    (e.g. "engagement ladder") regardless of file or line — compound matching is
    authoritative. known_sites is a second net, checked separately in check() where
    the file path and line number are available; it is never a requirement.
    """
    pattern, lookup, compounds = _deny_index(taxo)
    if pattern is None:
        return []
    compound_spans: list[tuple[int, int]] = []
    for phrase in compounds:
        for m in re.finditer(re.escape(phrase), line_text, re.IGNORECASE):
            compound_spans.append((m.start(), m.end()))
    matches = []
    for m in pattern.finditer(line_text):
        start, end = m.start(1), m.end(1)
        if any(cs <= start and end <= ce for cs, ce in compound_spans):
            continue
        term = lookup.get(m.group(1).lower())
        matches.append((start, end, m.group(1), term))
    return matches


def _known_sites(taxo: dict) -> set[str]:
    sites: set[str] = set()
    for term in taxo.get("terms", []) or []:
        for c in term.get("deny_list_exempt_compounds", []) or []:
            for site in c.get("known_sites", []) or []:
                sites.add(site)
    return sites


def _why(term: dict) -> str:
    """A short reason clause for the diagnostic — the house rule that a diagnostic
    states the fix, not just the symptom, extended to also state *why*."""
    definition = " ".join((term.get("definition") or "").split())
    if "." in definition:
        definition = definition.split(".")[0]
    return definition or str(term.get("term", ""))


def check(taxo: dict, root: Path = ROOT) -> int:
    """Walk `root`, report every surviving deny-listed match, return the problem count."""
    problems = 0
    known_sites = _known_sites(taxo)
    for path in walk(taxo, root=root):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        fm_lines, body_lines = split_frontmatter(text)
        for line_no, line_text in fm_lines + body_lines:
            for start, end, matched, term in deny_matches(line_text, taxo):
                if term is None:
                    continue
                if f"{rel}:{line_no}" in known_sites:
                    continue
                canonical = term.get("term")
                why = _why(term)
                print(
                    f"ERROR: {rel}:{line_no} '{matched}' is deny-listed — "
                    f"use '{canonical}' ({why})",
                    file=sys.stderr,
                )
                problems += 1
    return problems


# --selftest fixtures: embedded drift, written into a fresh tempfile.mkdtemp() tree per
# fixture, linted there, never inside ROOT (D-05 — permanent calibration, no repo state
# required). Each dict: id, path (repo-relative-style, written under the temp root),
# text, expect ("fail" or "pass"), why.
FIXTURES: list[dict] = [
    {
        "id": "denied-term-prose",
        "path": "notes/02-harnesses/fixture-tool.md",
        "text": "# Fixture\n\nThis report still uses the old layer terminology in prose.\n",
        "expect": "fail",
        "why": "'layer' is on the deny_list for term 'categories' — must fail.",
    },
    {
        "id": "exempt-path-skipped",
        "path": "upstream/some-clone/README.md",
        "text": "# Fixture\n\nThis old layer terminology lives under upstream/, which is "
        "skip_entirely — must not fail.\n",
        "expect": "pass",
        "why": "upstream/* matches exempt_paths.skip_entirely — the file is never walked.",
    },
]


def selftest(taxo: dict) -> tuple[int, int]:
    """Run FIXTURES against fresh temp trees; return (fixtures_run, problems)."""
    total_problems = 0
    for fx in FIXTURES:
        tmp_root = Path(tempfile.mkdtemp(prefix="check-taxonomy-selftest-"))
        try:
            target = tmp_root / fx["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(fx["text"], encoding="utf-8")
            problems = check(taxo, root=tmp_root)
            got = "fail" if problems else "pass"
            if got != fx["expect"]:
                print(
                    f"ERROR: fixture '{fx['id']}' expected {fx['expect']} but got "
                    f"{got} — {fx['why']}",
                    file=sys.stderr,
                )
                total_problems += 1
        finally:
            shutil.rmtree(tmp_root, ignore_errors=True)
    return len(FIXTURES), total_problems


def main() -> int:
    taxo = load_taxonomy()
    args = sys.argv[1:]
    valid = {"--check", "--selftest"}
    if len(args) > 1 or (args and args[0] not in valid):
        print("usage: check-taxonomy.py [--check|--selftest]", file=sys.stderr)
        return 2

    if args and args[0] == "--selftest":
        count, problems = selftest(taxo)
        print(f"{count} fixtures run, {problems} problem(s)")
        return 1 if problems else 0

    problems = check(taxo)
    files_checked = sum(1 for _ in walk(taxo))
    print(f"{files_checked} files checked, {problems} problem(s)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
