#!/usr/bin/env python3
"""Fail-hard lint for this repo's taxonomy vocabulary — reads taxonomy.yaml as the sole
source of truth and flags drift in current-state documents, extending the fail-hard
rule-3/rule-4 pattern the other two `--check` generators already enforce (methodology.md):
a hand-kept vocabulary drifts from what the ADRs actually decided, and you find out when
it's already wrong; a claim about which term is canonical is only as good as the check
that verifies it against the decision record.

    python3 scripts/check-taxonomy.py              # run the check (default)
    python3 scripts/check-taxonomy.py --check       # identical to the bare invocation
    python3 scripts/check-taxonomy.py --selftest    # run the embedded fixtures instead

Exit codes: 0 clean, 1 violations found (or a fixture that failed to discriminate),
2 unknown argument.

This script checks; it writes nothing into the repo under any invocation (D-07 — the
honest name).

The lint is EXPECTED to exit non-zero against the real repo as of Phase 2 — the red
findings are Phase 3's work queue, not a bug here. Only --selftest must be green at the
end of this phase (LINT-07, partial).

`--selftest` is PERMANENT calibration, not a pre-sweep formality (LINT-07, D-05,
methodology 5d): it must still pass after Phase 3 turns the real repo run green, which
is exactly the moment a silently-broken check would otherwise become invisible — a
lint nobody can watch fail is a lint nobody can trust to have caught anything.
"""
from __future__ import annotations

import copy
import fnmatch
import re
import shutil
import sys
import tempfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TAXONOMY = ROOT / "taxonomy.yaml"
FEATURE_REGISTRY_PATH = ROOT / "notes" / "cross-cutting" / "feature-taxonomy.md"

# A file containing this marker is generated output (comparisons/*.md, refs/index.md)
# and is never a lint target directly — its generator owns the vocabulary it emits
# (methodology rule 3). This is a backstop: exempt_paths.skip_entirely already lists
# comparisons/*, so this catches a newly generated file before anyone remembers to add
# its path there.
GENERATED_MARKER = "GENERATED by scripts/"

FRONTMATTER_KEY_RE = re.compile(r"^(\s*[A-Za-z0-9_.\-]+:)\s?")


def load_taxonomy(path: Path = TAXONOMY) -> dict:
    """Read taxonomy.yaml with the safe loader (matches both existing generators).

    Nothing the lint validates against may be hardcoded in this script: terms,
    deny-lists, compounds, and path patterns all come from this file (VOCAB-02).
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        sys.exit(f"cannot read {path}: {e}")
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as e:
        sys.exit(f"{path} is not valid YAML: {e}")
    if not isinstance(data, dict):
        sys.exit(f"{path} did not parse to a mapping")
    return data


def read_frontmatter(path: Path) -> dict | None:
    """Return the YAML frontmatter of a markdown file, or None if it has none.

    Duplicated verbatim from build-refs-index.py rather than imported: ten lines, and
    this script validates a different schema — coupling would mean one script's
    vocabulary change breaking another (same rationale as build-refs-index.py's own
    copy of this function).
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    data = yaml.safe_load(text[4:end])
    return data if isinstance(data, dict) else None


def _load_feature_registry() -> list[dict]:
    """Duplicated from build-tool-index.py's `_load_feature_registry` (~15 lines)
    rather than imported: the two scripts must not couple, and the precedent is
    already established by this script's own `read_frontmatter` duplication. Always
    reads the REAL repo's registry (FEATURE_REGISTRY_PATH, fixed at ROOT) regardless
    of which tree `check_feature_registry` is scanning — the registry is a stable
    single source of truth, not something a --selftest fixture tree redefines.

    T-02-05 (Tampering, mitigate): exits non-zero with a named diagnostic when the
    yaml block is missing, unparsable, or an entry lacks `id`/`block` — mirroring the
    generator's fail-fast rather than silently building an empty/partial key set.
    """
    try:
        text = FEATURE_REGISTRY_PATH.read_text(encoding="utf-8")
    except OSError as e:
        sys.exit(f"feature taxonomy missing: {FEATURE_REGISTRY_PATH} ({e})")
    m = re.search(r"```yaml\n(.*?)```", text, re.DOTALL)
    if not m:
        sys.exit(f"feature taxonomy has no ```yaml block: {FEATURE_REGISTRY_PATH}")
    try:
        data = yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        sys.exit(f"feature taxonomy YAML unparsable: {e}")
    entries = (data or {}).get("features")
    if not isinstance(entries, list) or not entries:
        sys.exit("feature taxonomy: `features:` must be a non-empty list")
    known_blocks = {
        "harness_features",
        "workflow_features",
        "memory_features",
        "model_features",
        "environment_features",
    }
    for e in entries:
        for req in ("id", "block"):
            if req not in e:
                sys.exit(f"feature taxonomy entry missing `{req}`: {e}")
        if e["block"] not in known_blocks:
            sys.exit(
                f"feature taxonomy entry `{e['id']}` has unknown block `{e['block']}` "
                f"(known: {sorted(known_blocks)})"
            )
    return entries


def check_feature_registry(taxo: dict, root: Path = ROOT) -> int:
    """Frontmatter `harness_features:` / `workflow_features:` / `memory_features:` /
    `model_features:` keys must resolve against the feature registry (LINT-04a,
    D-06a). Escalation is the point: build-tool-index.py's `render_features` /
    `render_models` etc. only WARN on an unknown key and silently drop it from the
    generated matrix — tolerable for a generator, not for a fail-hard lint, so this
    check turns the same condition into an ERROR.

    Not affected by the deny-list prose scanner's frontmatter-key stripping
    (`split_frontmatter`) — that scanner reads prose; this reads parsed frontmatter
    directly, a different thing entirely, and the two must not be merged.
    """
    problems = 0
    registry = _load_feature_registry()
    valid_by_block: dict[str, set[str]] = {}
    for e in registry:
        valid_by_block.setdefault(e["block"], set()).add(e["id"])
    blocks = (
        "harness_features",
        "workflow_features",
        "memory_features",
        "model_features",
        "environment_features",
    )
    for path in walk(taxo, root=root):
        rel = path.relative_to(root).as_posix()
        if not rel.startswith("notes/"):
            continue
        if path.name.startswith("_") or path.name == "index.md":
            continue  # templates and layer indexes are not reports (mirrors collect())
        fm = read_frontmatter(path)
        if not fm:
            continue
        for block in blocks:
            mapping = fm.get(block)
            if not isinstance(mapping, dict):
                continue
            valid_keys = valid_by_block.get(block, set())
            for key in mapping:
                if key not in valid_keys:
                    print(
                        f"ERROR: {rel} '{key}' is unregistered in block "
                        f"'{block}' — add it to notes/cross-cutting/"
                        f"feature-taxonomy.md or fix the spelling",
                        file=sys.stderr,
                    )
                    problems += 1
    return problems


def is_exempt(rel: str, taxo: dict) -> str | None:
    """Return the exempt_paths pattern matching `rel`, or None if it is a lint target.

    Only skip_entirely and append_only make a file invisible to the walk; body_exempt
    and adr_title_exempt are per-line exemptions applied inside check(), not here.
    """
    exempt = taxo.get("exempt_paths", {}) or {}
    patterns = (exempt.get("skip_entirely", []) or []) + (exempt.get("append_only", []) or [])
    for pat in patterns:
        if fnmatch.fnmatch(rel, pat):
            return pat
    return None


def walk(taxo: dict, root: Path = ROOT):
    """Yield every current-state markdown file under `root`: not exempt, not generated."""
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).as_posix()
        if is_exempt(rel, taxo):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        if GENERATED_MARKER in text:
            continue
        yield path


def split_frontmatter(text: str) -> tuple[list[tuple[int, str]], list[tuple[int, str]]]:
    """Split a file's text into (frontmatter_lines, body_lines), each a list of
    (1-indexed line number, scannable text).

    The prose scanner reads BODY lines as-is, plus frontmatter lines with their leading
    `key:` token stripped — a frontmatter key is schema (governed by schema_renames,
    Plan 02), not prose, so `layer: 4` must not flag every report while the key rename
    is still pending (dormancy contract). A frontmatter *value* or trailing comment is
    prose and stays in scope, hence the strip-not-drop.
    """
    lines = text.splitlines()
    frontmatter_lines: list[tuple[int, str]] = []
    body_start = 0
    if lines and lines[0] == "---":
        end = None
        for i in range(1, len(lines)):
            if lines[i] == "---":
                end = i
                break
        if end is not None:
            for i in range(1, end):
                stripped = FRONTMATTER_KEY_RE.sub("", lines[i], count=1)
                frontmatter_lines.append((i + 1, stripped))
            body_start = end + 1
    body_lines = [(i + 1, lines[i]) for i in range(body_start, len(lines))]
    return frontmatter_lines, body_lines


def _raw_frontmatter_lines(text: str) -> list[tuple[int, str]]:
    """The frontmatter block's lines UNSTRIPPED (unlike `split_frontmatter`, which
    strips the leading `key:` token for prose scanning) — check_schema_renames needs
    the actual key text to detect `old_key:` / `new_key:` at column 0."""
    lines = text.splitlines()
    result: list[tuple[int, str]] = []
    if lines and lines[0] == "---":
        end = None
        for i in range(1, len(lines)):
            if lines[i] == "---":
                end = i
                break
        if end is not None:
            for i in range(1, end):
                result.append((i + 1, lines[i]))
    return result


def _deny_index(taxo: dict) -> tuple[re.Pattern | None, dict, list[str]]:
    """Build (and cache on `taxo`) the single alternation regex over every deny-listed
    term, longest-first so a matched compound like "cross-layer" reports as itself
    rather than also as "layer" — `\\b` on the whole alternative plus finditer's
    non-overlapping scan means the embedded "layer" is never independently re-tried
    once "cross-layer" has consumed that span.
    """
    cached = taxo.get("_deny_index")
    if cached is not None:
        return cached
    entries: list[tuple[str, dict]] = []
    seen: set[str] = set()
    for term in taxo.get("terms", []) or []:
        for d in term.get("deny_list", []) or []:
            if d.endswith(":"):
                # Frontmatter-key entries (e.g. "kind:") are schema, not prose — Plan
                # 02's schema-rename check owns these. Known false positive this
                # exclusion prevents: notes/05-memory/ai-memory.md:90
                # ("Table stakes in the kind: store + retrieve + MCP.") — ordinary
                # prose, not the report frontmatter key.
                continue
            key = d.lower()
            if key in seen:
                continue
            seen.add(key)
            entries.append((d, term))
    entries.sort(key=lambda e: -len(e[0]))
    pattern = None
    if entries:
        alt = "|".join(re.escape(d) for d, _ in entries)
        pattern = re.compile(rf"\b({alt})\b", re.IGNORECASE)
    lookup = {d.lower(): term for d, term in entries}
    compounds = [
        c["compound"]
        for term in taxo.get("terms", []) or []
        for c in term.get("deny_list_exempt_compounds", []) or []
    ]
    result = (pattern, lookup, compounds)
    taxo["_deny_index"] = result
    return result


def _phrase_spans(line_text: str, phrases: list[str]) -> list[tuple[int, int]]:
    """Spans of each phrase's (case-insensitive) occurrences on this line. Shared by
    `deny_matches` (all deny_list_exempt_compounds, unconditionally) and `check`
    (only the specific compound(s) recorded as a known_sites entry at this exact
    file:line — CR-01) so both exemptions use the same span-containment logic."""
    spans: list[tuple[int, int]] = []
    for phrase in phrases:
        for m in re.finditer(re.escape(phrase), line_text, re.IGNORECASE):
            spans.append((m.start(), m.end()))
    return spans


def deny_matches(line_text: str, taxo: dict) -> list[tuple[int, int, str, dict | None]]:
    """Find deny-listed terms in one line of prose.

    Skips a match falling inside any deny_list_exempt_compounds[].compound phrase
    (e.g. "engagement ladder") regardless of file or line — compound matching is
    authoritative. known_sites is a second net, checked separately in check() where
    the file path and line number are available; it is never a requirement.
    """
    pattern, lookup, compounds = _deny_index(taxo)
    if pattern is None:
        return []
    compound_spans = _phrase_spans(line_text, compounds)
    matches = []
    for m in pattern.finditer(line_text):
        start, end = m.start(1), m.end(1)
        if any(cs <= start and end <= ce for cs, ce in compound_spans):
            continue
        term = lookup.get(m.group(1).lower())
        matches.append((start, end, m.group(1), term))
    return matches


def _matches_any(rel: str, taxo: dict, key: str) -> bool:
    patterns = (taxo.get("exempt_paths", {}) or {}).get(key, []) or []
    return any(fnmatch.fnmatch(rel, pat) for pat in patterns)


H1_RE = re.compile(r"^#(?!#)")


def _first_h1(body_lines: list[tuple[int, str]]) -> tuple[int, str] | None:
    """The first line starting with a single `#` — an ADR's title line (D-04)."""
    for line_no, text in body_lines:
        if H1_RE.match(text):
            return line_no, text
    return None


FENCE_RE = re.compile(r"^\s*```")


def _line_in_fence_map(lines: list[str]) -> list[bool]:
    """True for every line inside (or delimiting) a fenced ```code block```, tracking
    fence state across lines — a single-line backtick count can't tell "inside a fence"
    from "two separate inline spans"."""
    in_fence = False
    flags = []
    for line in lines:
        if FENCE_RE.match(line):
            flags.append(True)  # the delimiter line itself is code context
            in_fence = not in_fence
        else:
            flags.append(in_fence)
    return flags


INLINE_CODE_RE = re.compile(r"`[^`]+`")


def _inline_code_spans(line: str) -> list[tuple[int, int]]:
    """Single-backtick inline code spans on this line."""
    return [(m.start(), m.end()) for m in INLINE_CODE_RE.finditer(line)]


ADR_FILENAME_RE = re.compile(r"(?:adrs/)?\d{4}-[a-z0-9][a-z0-9-]*\.md")


def _adr_filename_spans(line: str) -> list[tuple[int, int]]:
    """Tokens that look like an ADR filename reference (adrs/NNNN-....md or a bare
    NNNN-....md)."""
    return [(m.start(), m.end()) for m in ADR_FILENAME_RE.finditer(line)]


def _in_any_span(start: int, end: int, spans: list[tuple[int, int]]) -> bool:
    return any(s <= start and end <= e for s, e in spans)


# One predicate per taxonomy.yaml carve_outs[].id, dispatched by id so adding a
# carve-out to the yaml has a single obvious landing site here. Each predicate takes
# the match context dict built in check() and returns True to exempt that match.
def _carveout_adr_filenames(ctx: dict) -> bool:
    return _in_any_span(ctx["start"], ctx["end"], ctx["adr_spans"])


def _carveout_inline_code(ctx: dict) -> bool:
    return ctx["fence"] or _in_any_span(ctx["start"], ctx["end"], ctx["code_spans"])


def _carveout_adr_body_prose(ctx: dict) -> bool:
    return ctx["body_exempt_file"] and not ctx["is_title_line"]


def _carveout_pre_sweep_material(ctx: dict) -> bool:
    # Resolves to exempt_paths.skip_entirely/append_only, already applied in walk() —
    # this predicate only exists so the id is not unimplemented. After Task 3's
    # narrowing, this carve-out exempts no file that is not enumerated in exempt_paths.
    return is_exempt(ctx["rel"], ctx["taxo"]) is not None


CARVE_OUT_PREDICATES = {
    "adr-filenames": _carveout_adr_filenames,
    "inline-code": _carveout_inline_code,
    "adr-body-prose": _carveout_adr_body_prose,
    "pre-sweep-material": _carveout_pre_sweep_material,
}


def assert_carveouts_implemented(taxo: dict) -> None:
    ids = [c["id"] for c in taxo.get("carve_outs", []) or []]
    missing = [i for i in ids if i not in CARVE_OUT_PREDICATES]
    if missing:
        sys.exit(f"carve_outs in taxonomy.yaml with no predicate implemented: {missing}")


def _known_sites(taxo: dict) -> dict[str, list[str]]:
    """Map "file:line" -> the compound phrase(s) recorded as known at that site.

    CR-01: a known_sites entry only vouches for the SPAN of the compound it was
    recorded for (e.g. "enforcement ladder"), not the whole line — check() uses
    this mapping together with `_phrase_spans` to compute that compound's actual
    span on the file's real line text before treating a match as exempt. An
    unrelated deny-listed word matched elsewhere on the same line (e.g. a bare
    "layer") must still flag; it was never the compound this site documents.
    """
    sites: dict[str, list[str]] = {}
    for term in taxo.get("terms", []) or []:
        for c in term.get("deny_list_exempt_compounds", []) or []:
            compound = c.get("compound")
            for site in c.get("known_sites", []) or []:
                sites.setdefault(site, []).append(compound)
    return sites


def _why(term: dict) -> str:
    """A short reason clause for the diagnostic — the house rule that a diagnostic
    states the fix, not just the symptom, extended to also state *why*."""
    definition = " ".join((term.get("definition") or "").split())
    if "." in definition:
        definition = definition.split(".")[0]
    return definition or str(term.get("term", ""))


# --- LINT-02: stale category names/numbering, strict reference-format enforcement ---
# Every rule below derives from taxonomy.yaml's `categories:` and `reference_formats:`
# blocks — no vocabulary is invented here (methodology rule 4). `stack` is a
# split_meaning_terms entry with lint_enforceable: false; this check never touches it
# (nor does any other check in this script) — 'stack' is an accepted gap, caught by
# readers, not a heuristic to attempt.

MIDDLE_DOT = "·"  # U+00B7 MIDDLE DOT — reference_formats.table_index_note

# Separator glyphs reference_formats.table_index_note names as wrong ("not a hyphen,
# bullet, or other separator") plus the two dash variants and a colon. The period form
# ("### N. Name", taxonomy.md's live section headings) is deliberately excluded — it is
# canonical prose, not a table-index reference, and flagging it would be wrong.
WRONG_SEPARATORS = "-–—•:"  # hyphen, en dash, em dash, bullet, colon


def _category_name_alternation(taxo: dict) -> str:
    names = [c["name"] for c in taxo.get("categories", []) or []]
    return "|".join(re.escape(n) for n in sorted(names, key=len, reverse=True))


def _table_index_regexes(taxo: dict) -> tuple[re.Pattern, re.Pattern]:
    """Both the wrong-separator and canonical-pairing regexes, over the canonical
    category names taken from taxonomy.yaml (no hardcoded name list)."""
    names_alt = _category_name_alternation(taxo)
    wrong = re.compile(
        rf"(?<!\d)(\d)\s*([{re.escape(WRONG_SEPARATORS)}])\s*({names_alt})\b"
    )
    canonical = re.compile(rf"(?<!\d)(\d) {MIDDLE_DOT} ({names_alt})\b")
    return wrong, canonical


# Prose/compound form: reference_formats.prose ("category N") / .compound
# ("category-N"). Case-insensitive match so the check can also judge whether an
# occurrence's actual case is canonical.
CATEGORY_NUM_RE = re.compile(r"\b(category)([ \t-]*)(\d)", re.IGNORECASE)


def _orthographic_capital_ok(line_text: str, start: int) -> bool:
    """True if the match at `start` is line-, list-item-, heading-, or table-cell-
    initial, or follows a sentence terminator — capitalised by English orthography,
    not by vocabulary drift. This is the discretionary reading of `enforcement: strict`
    02-CONTEXT.md reserves to the executor; disagree with it explicitly, don't guess."""
    stripped = line_text[:start].strip()
    if stripped == "":
        return True  # line-initial (only leading whitespace before the match)
    if re.fullmatch(r"[-*+]|\d+[.)]|#{1,6}|\|", stripped):
        return True  # list-item-, heading-, or table-cell-initial leader
    if stripped[-1] in ".!?":
        return True  # follows a sentence terminator
    return False


def check_reference_formats(taxo: dict, root: Path = ROOT) -> int:
    """Flag stale name/number pairings, non-canonical table-index separators, and
    non-canonical prose/compound category references (LINT-02).

    Table-index matching is restricted to markdown TABLE ROWS (a line that, once
    stripped, starts with `|`) — the only in-repo occurrences of the "N <sep> Name"
    shape are table cells (`| 2 · Harnesses |`); layer index.md files' H1 titles use
    the same digit-dash-name shape for an unrelated purpose (e.g. "# Layer 5 —
    Execution environments") and must not be double-counted as a table-index
    violation — they are already flagged by the deny-list check for the word "Layer".
    This scoping is Claude's Discretion per 02-CONTEXT.md ("how the strict
    reference-format check distinguishes table cells from prose contexts").
    """
    problems = 0
    name_to_num = {c["name"]: c["number"] for c in taxo.get("categories", []) or []}
    wrong_re, canonical_re = _table_index_regexes(taxo)
    for path in walk(taxo, root=root):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        fm_lines, body_lines = split_frontmatter(text)

        body_exempt_file = _matches_any(rel, taxo, "body_exempt")
        title_exempt_file = _matches_any(rel, taxo, "adr_title_exempt")
        title_line_no = None
        if body_exempt_file and not title_exempt_file:
            h1 = _first_h1(body_lines)
            title_line_no = h1[0] if h1 else None

        fence_flags = _line_in_fence_map([t for _, t in body_lines])
        fence_by_line = {ln: fence_flags[i] for i, (ln, _t) in enumerate(body_lines)}

        for line_no, line_text in fm_lines + body_lines:
            code_spans = _inline_code_spans(line_text)
            adr_spans = _adr_filename_spans(line_text)
            is_title_line = bool(body_exempt_file and line_no == title_line_no)
            fence = fence_by_line.get(line_no, False)

            def _exempt(start: int, end: int) -> bool:
                ctx = {
                    "rel": rel,
                    "taxo": taxo,
                    "start": start,
                    "end": end,
                    "body_exempt_file": body_exempt_file,
                    "is_title_line": is_title_line,
                    "fence": fence,
                    "code_spans": code_spans,
                    "adr_spans": adr_spans,
                }
                return any(pred(ctx) for pred in CARVE_OUT_PREDICATES.values())

            if line_text.lstrip().startswith("|"):
                for m in wrong_re.finditer(line_text):
                    if _exempt(*m.span()):
                        continue
                    num, sep, name = m.group(1), m.group(2), m.group(3)
                    print(
                        f"ERROR: {rel}:{line_no} '{m.group(0).strip()}' uses "
                        f"separator '{sep}' — canonical table-index form is "
                        f"'{num} {MIDDLE_DOT} {name}' (U+00B7, single space each "
                        f"side, reference_formats.table_index)",
                        file=sys.stderr,
                    )
                    problems += 1
                for m in canonical_re.finditer(line_text):
                    if _exempt(*m.span()):
                        continue
                    num, name = int(m.group(1)), m.group(2)
                    canonical_num = name_to_num.get(name)
                    if canonical_num is not None and num != canonical_num:
                        print(
                            f"ERROR: {rel}:{line_no} '{m.group(0)}' pairs a "
                            f"category name with the pre-ADR-0007 number — "
                            f"canonical is '{canonical_num} {MIDDLE_DOT} {name}'",
                            file=sys.stderr,
                        )
                        problems += 1

            for m in CATEGORY_NUM_RE.finditer(line_text):
                start, end = m.start(1), m.end(3)
                if _exempt(start, end):
                    continue
                word, sep, digit = m.group(1), m.group(2), m.group(3)
                case_ok = word == "category" or (
                    word == "Category" and _orthographic_capital_ok(line_text, start)
                )
                sep_ok = sep in (" ", "-")
                if not (case_ok and sep_ok):
                    print(
                        f"ERROR: {rel}:{line_no} '{line_text[start:end]}' is not "
                        f"the canonical category reference form — use "
                        f"'category {digit}' (prose) or 'category-{digit}' "
                        f"(compound); reference_formats, strict enforcement",
                        file=sys.stderr,
                    )
                    problems += 1
    return problems


def check_unreadable_files(taxo: dict, root: Path = ROOT) -> int:
    """WR-03: a file that fails to decode (bad encoding, permissions, etc.) is
    silently dropped by `walk()`'s `except (OSError, UnicodeDecodeError): continue`
    — invisible to every checker AND to `files_checked`, with zero diagnostic. That
    directly contradicts this lint's own fail-hard framing. Runs its own scan
    (mirroring `walk()`'s exemption logic, not `walk()` itself) so a coverage gap is
    reported — and counted — exactly once per run rather than once per checker that
    happens to call `walk()`.
    """
    problems = 0
    for path in sorted(root.rglob("*.md")):
        rel = path.relative_to(root).as_posix()
        if is_exempt(rel, taxo):
            continue
        try:
            path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as e:
            print(
                f"ERROR: {rel} unreadable, excluded from lint coverage: {e}",
                file=sys.stderr,
            )
            problems += 1
    return problems


def check(taxo: dict, root: Path = ROOT) -> int:
    """Walk `root`, report every surviving deny-listed match, return the problem count."""
    problems = 0
    known_sites = _known_sites(taxo)
    for path in walk(taxo, root=root):
        rel = path.relative_to(root).as_posix()
        text = path.read_text(encoding="utf-8")
        fm_lines, body_lines = split_frontmatter(text)

        body_exempt_file = _matches_any(rel, taxo, "body_exempt")
        title_exempt_file = _matches_any(rel, taxo, "adr_title_exempt")
        title_line_no = None
        if body_exempt_file and not title_exempt_file:
            h1 = _first_h1(body_lines)
            title_line_no = h1[0] if h1 else None

        fence_flags = _line_in_fence_map([t for _, t in body_lines])
        fence_by_line = {ln: fence_flags[i] for i, (ln, _t) in enumerate(body_lines)}

        for line_no, line_text in fm_lines + body_lines:
            code_spans = _inline_code_spans(line_text)
            adr_spans = _adr_filename_spans(line_text)
            is_title_line = bool(body_exempt_file and line_no == title_line_no)
            fence = fence_by_line.get(line_no, False)
            for start, end, matched, term in deny_matches(line_text, taxo):
                if term is None:
                    continue
                ctx = {
                    "rel": rel,
                    "line_no": line_no,
                    "line_text": line_text,
                    "start": start,
                    "end": end,
                    "matched": matched,
                    "taxo": taxo,
                    "body_exempt_file": body_exempt_file,
                    "is_title_line": is_title_line,
                    "fence": fence,
                    "code_spans": code_spans,
                    "adr_spans": adr_spans,
                }
                if any(pred(ctx) for pred in CARVE_OUT_PREDICATES.values()):
                    continue
                known_compounds_here = known_sites.get(f"{rel}:{line_no}", [])
                if known_compounds_here and _in_any_span(
                    start, end, _phrase_spans(line_text, known_compounds_here)
                ):
                    continue
                canonical = term.get("term")
                why = _why(term)
                print(
                    f"ERROR: {rel}:{line_no} '{matched}' is deny-listed — "
                    f"use '{canonical}' ({why})",
                    file=sys.stderr,
                )
                problems += 1
    return problems


# --- LINT-05: the unapplied-decoder check (ADR-0015's schema_renames) ---
# The frontmatter-key half of the decoder is governed by `schema_renames[].status`,
# not a CLI flag and not "prose only until Phase 3" — a status field keeps the state
# in the recorded contract (where `executes_in: phase-3` already lives) rather than in
# whoever typed the command. Two-sided so the rule is live in BOTH states, not dead
# code waiting for Phase 3.
_VALID_RENAME_STATUSES = {"pending", "applied"}


def check_schema_renames(taxo: dict, root: Path = ROOT) -> int:
    """`pending`: the OLD key is current; a premature NEW key fails (both land in one
    Phase-3 atomic commit, ADR-0015 § Sequencing). `applied`: the NEW key is current;
    a surviving OLD key fails as an unapplied decoder.

    T-02-06 (Spoofing, mitigate): only the literals `pending`/`applied` are accepted —
    any other value is a startup error, so a typo can't silently disable this check.

    Scans FRONTMATTER only (via `_raw_frontmatter_lines`, not the prose-stripped
    `split_frontmatter` lines) — this is deliberately disjoint from `check()`'s prose
    scanner, which already excludes colon-suffixed deny entries like `kind:` from
    prose at the regex-build step (`_deny_index`). That's what lets the recorded
    false positive — `notes/05-memory/ai-memory.md:90`'s "Table stakes
    in the kind: store + retrieve + MCP." (taxonomy.yaml, term `types`,
    false_positive_notes) — pass without a per-site carve-out: prose "kind:" is never
    even a candidate for this check, because this check never looks at body text.
    """
    problems = 0
    renames = taxo.get("schema_renames", []) or []
    for entry in renames:
        status = entry.get("status")
        if status not in _VALID_RENAME_STATUSES:
            sys.exit(
                f"taxonomy.yaml schema_renames[old={entry.get('old')!r}] has "
                f"invalid status {status!r} — must be one of "
                f"{sorted(_VALID_RENAME_STATUSES)}"
            )

    for path in walk(taxo, root=root):
        rel = path.relative_to(root).as_posix()
        if not rel.startswith("notes/"):
            continue
        text = path.read_text(encoding="utf-8")
        raw_lines = _raw_frontmatter_lines(text)
        if not raw_lines:
            continue
        fm = read_frontmatter(path)

        for entry in renames:
            old, new, status = entry["old"], entry["new"], entry["status"]
            # kind -> type is scoped to category-5 reports plus the shared template
            # (both explicitly listed in this entry's own `scope:`); layer -> category
            # applies to every notes/ report and template, so no extra gate — refs/'s
            # unrelated `kind:` vocabulary never reaches here at all (refs/* is
            # exempt_paths.skip_entirely, so walk() never yields it).
            if old == "kind":
                # WR-01: read whichever category key is CURRENTLY active, not the
                # pre-rename name specifically — once layer->category lands (both
                # renames land in the same Phase-3 atomic commit), fm.get("layer")
                # alone would return None for every real report and this gate
                # would go silently blind to the applied-branch check below.
                category_value = (
                    (fm.get("category") or fm.get("layer")) if isinstance(fm, dict) else None
                )
                # ADR-0020 (2026-08-22): the type-carrying categories are 5 and 6
                in_scope = rel.endswith("_template-tool-report.md") or category_value in (
                    5,
                    "5",
                    6,
                    "6",
                )
                if not in_scope:
                    continue
            old_re = re.compile(rf"^{re.escape(old)}:(\s|$)")
            new_re = re.compile(rf"^{re.escape(new)}:(\s|$)")
            for line_no, line_text in raw_lines:
                if status == "pending" and new_re.match(line_text):
                    print(
                        f"ERROR: {rel}:{line_no} '{new}:' is a premature "
                        f"'{new}:' key — status is pending; both '{old}:' and "
                        f"'{new}:' land in one Phase-3 atomic commit (ADR-0015 "
                        f"§ Sequencing)",
                        file=sys.stderr,
                    )
                    problems += 1
                elif status == "applied" and old_re.match(line_text):
                    print(
                        f"ERROR: {rel}:{line_no} superseded key '{old}:' — "
                        f"ADR-0015's decoder is not fully applied; rename to "
                        f"'{new}:'",
                        file=sys.stderr,
                    )
                    problems += 1
    return problems


def _with_schema_renames_applied(taxo: dict) -> dict:
    """A deep-copied taxo with every schema_renames[].status flipped to 'applied' —
    used by the 'old-key-after-rename-applied' fixture to prove the dormant half of
    check_schema_renames discriminates NOW, on demand, rather than only in Phase 3."""
    patched = copy.deepcopy(taxo)
    for entry in patched.get("schema_renames", []) or []:
        entry["status"] = "applied"
    patched.pop("_deny_index", None)  # cached on the original taxo; don't share it
    return patched


def _with_schema_renames_pending(taxo: dict) -> dict:
    """A deep-copied taxo with every schema_renames[].status flipped to 'pending' —
    the symmetric counterpart to `_with_schema_renames_applied`. Used by the
    'old-key-while-pending' and 'premature-renamed-key' fixtures so they test the
    pending branch of check_schema_renames on its own terms rather than relying on
    the live taxonomy.yaml's status happening to still read 'pending' — a fixture
    without this patch went silently inverted the moment Phase 3's atomic commit
    flipped the real file to 'applied' (found executing plan 03-02, 2026-08-19)."""
    patched = copy.deepcopy(taxo)
    for entry in patched.get("schema_renames", []) or []:
        entry["status"] = "pending"
    patched.pop("_deny_index", None)  # cached on the original taxo; don't share it
    return patched


def _with_extra_known_site(site: str, compound: str = "enforcement ladder"):
    """A taxo_patch factory: a deep-copied taxo with `site` (an exact "file:line"
    string) appended to `compound`'s known_sites list — used by the
    'known-site-scoped-to-compound-span' fixture (CR-01) to reproduce the real
    gsd-core.md:191 shape (a known-site compound sharing a line with an unrelated,
    genuinely deny-listed word) without depending on real-repo line numbers."""

    def patch(taxo: dict) -> dict:
        patched = copy.deepcopy(taxo)
        for term in patched.get("terms", []) or []:
            for c in term.get("deny_list_exempt_compounds", []) or []:
                if c.get("compound") == compound:
                    c.setdefault("known_sites", []).append(site)
        patched.pop("_deny_index", None)  # cached on the original taxo; don't share it
        return patched

    return patch


# --selftest fixtures: embedded drift, written into a fresh tempfile.mkdtemp() tree per
# fixture, linted there, never inside ROOT (D-05 — permanent calibration, no repo state
# required). Each dict: id, path (repo-relative-style, written under the temp root),
# text, expect ("fail" or "pass"), why.
FIXTURES: list[dict] = [
    {
        "id": "denied-term-prose",
        "path": "notes/02-harnesses/fixture-tool.md",
        "text": "# Fixture\n\nThis report still uses the old layer terminology in prose.\n",
        "expect": "fail",
        "why": "'layer' is on the deny_list for term 'categories' — must fail.",
    },
    {
        "id": "exempt-path-skipped",
        "path": "upstream/some-clone/README.md",
        "text": "# Fixture\n\nThis old layer terminology lives under upstream/, which is "
        "skip_entirely — must not fail.\n",
        "expect": "pass",
        "why": "upstream/* matches exempt_paths.skip_entirely — the file is never walked.",
    },
    {
        "id": "inline-code-span",
        "path": "notes/02-harnesses/fixture-code.md",
        "text": "# Fixture\n\nThe old `layer` identifier appears here only inside code "
        "formatting.\n",
        "expect": "pass",
        "why": "the match is inside a single-backtick inline code span — carve-out "
        "inline-code.",
    },
    {
        "id": "adr-filename-link",
        "path": "notes/04-workflow-frameworks/fixture-link.md",
        "text": "# Fixture\n\nSee [ADR-0003](../../adrs/0003-environments-stay-a-rung.md) "
        "for background.\n",
        "expect": "pass",
        "why": "'rung' is inside an adrs/NNNN-....md filename token — carve-out "
        "adr-filenames.",
    },
    {
        "id": "adr-body-prose",
        "path": "adrs/9999-fixture-decision.md",
        "text": "# ADR-9999 — Fixture decision\n\n## Decision\n\nThis body discusses the "
        "old layer terminology as historical record.\n",
        "expect": "pass",
        "why": "banned word is in an adrs/*.md BODY line, not the title — carve-out "
        "adr-body-prose.",
    },
    {
        "id": "adr-title-linted",
        "path": "adrs/9998-fixture-title.md",
        "text": "# ADR-9998 — The old layer decision\n\n## Decision\n\nBody text, clean, "
        "no banned words here.\n",
        "expect": "fail",
        "why": "banned word is in the H1 TITLE line of an ADR path not listed in "
        "adr_title_exempt — titles are still linted (D-04).",
    },
    {
        "id": "exempt-compound-ladder",
        "path": "notes/04-workflow-frameworks/fixture-ladder.md",
        "text": "# Fixture\n\nHere the engagement ladder concept appears, not the "
        "taxonomy's own top-level grouping.\n",
        "expect": "pass",
        "why": "'engagement ladder' is a deny_list_exempt_compounds phrase, at a line "
        "not in known_sites — compound matching alone must hold.",
    },
    {
        "id": "known-site-scoped-to-compound-span",
        "path": "notes/04-workflow-frameworks/fixture-known-site-scope.md",
        "text": "# Fixture\n\nThe enforcement ladder is fine here, but the layer's "
        "sharpest categories concept is not.\n",
        "expect": "fail",
        "taxo_patch": _with_extra_known_site(
            "notes/04-workflow-frameworks/fixture-known-site-scope.md:3"
        ),
        "why": "CR-01: a known_sites entry recorded for the 'enforcement ladder' "
        "compound at this exact file:line must only shield matches falling inside "
        "that compound's own span — the independent, genuinely deny-listed 'layer' "
        "match elsewhere on the same line is unrelated and must still fail. "
        "Reproduces the real notes/04-workflow-frameworks/gsd-core.md:191 shape "
        "(compound + unrelated violation sharing a line) without depending on "
        "real-repo line numbers.",
    },
    {
        "id": "known-site-scoped-to-compound-span-memory-layer",
        "path": "notes/05-memory/fixture-memory-layer-scope.md",
        "text": "# Fixture\n\nThe memory layer is fine here, but the layer's "
        "sharpest categories concept is not.\n",
        "expect": "fail",
        "taxo_patch": _with_extra_known_site(
            "notes/05-memory/fixture-memory-layer-scope.md:3",
            compound="memory layer",
        ),
        "why": "WR-02: calibrates one of the 7 compounds added in 60e9b97 (chosen "
        "per WR-01, the riskiest of the seven since it is semantically adjacent to "
        "this repo's own category 5) against the same span-scoping proof CR-01 "
        "already established for 'enforcement ladder' — a known_sites entry "
        "recorded for 'memory layer' at this exact file:line must only shield "
        "matches falling inside that compound's own span; the independent, "
        "genuinely deny-listed bare 'layer' match elsewhere on the same line is "
        "unrelated and must still fail.",
    },
    {
        "id": "cross-cutting-not-cross-layer",
        "path": "notes/cross-cutting/fixture-cutting.md",
        "text": "# Fixture\n\nThis document uses cross-cutting concerns terminology "
        "throughout, nothing else.\n",
        "expect": "pass",
        "why": "'cross-cutting' is a distinct compound from 'cross-layer' and carries "
        "no banned word — the two must not be conflated.",
    },
    {
        "id": "stale-numbering-pairing",
        "path": "notes/03-execution-environments/fixture-stale-numbering.md",
        "text": "# Fixture\n\n| Idx | Note |\n|---|---|\n"
        "| 5 · Execution environments | wrong pairing |\n",
        "expect": "fail",
        "why": "'5 · Execution environments' pairs the canonical name with the "
        "pre-ADR-0007 number (canonical is 3) — LINT-02 pairing check.",
    },
    {
        "id": "wrong-separator-table-index",
        "path": "notes/02-harnesses/fixture-wrong-separator.md",
        "text": "# Fixture\n\n| Idx | Note |\n|---|---|\n"
        "| 2 - Harnesses | wrong separator |\n",
        "expect": "fail",
        "why": "a hyphen instead of U+00B7 fails reference_formats.table_index's "
        "strict separator enforcement, even though the pairing (2, Harnesses) is "
        "correct.",
    },
    {
        "id": "sentence-initial-category-ok",
        "path": "notes/04-workflow-frameworks/fixture-sentence-initial.md",
        "text": "# Fixture\n\nCategory 2 covers harnesses tooling in this repo.\n",
        "expect": "pass",
        "why": "line-initial 'Category' is orthographic capitalisation, not "
        "vocabulary drift — the documented exception to strict enforcement.",
    },
    {
        "id": "unregistered-feature-key",
        "path": "notes/02-harnesses/fixture-bad-feature-key.md",
        "text": "---\nname: fixture-tool\nharness_features:\n  totally_invented_key_xyz: true\n"
        "---\n\n# Fixture\n\nBody text, clean.\n",
        "expect": "fail",
        "why": "'totally_invented_key_xyz' resolves against no entry in the feature "
        "taxonomy's `features` block — LINT-04a.",
    },
    {
        "id": "registered-feature-key",
        "path": "notes/02-harnesses/fixture-good-feature-key.md",
        "text": "---\nname: fixture-tool\nharness_features:\n  mcp: true\n---\n\n# Fixture\n\n"
        "Body text, clean.\n",
        "expect": "pass",
        "why": "'mcp' genuinely exists in the feature taxonomy's `features` block "
        "(applies_to: [2]) — a real key must resolve cleanly.",
    },
    {
        "id": "old-key-while-pending",
        "path": "notes/02-harnesses/fixture-old-key-pending.md",
        "text": "---\nlayer: 2\n---\n\n# Fixture\n\nOld key usage, no drift.\n",
        "expect": "pass",
        "taxo_patch": _with_schema_renames_pending,
        "why": "status is pending — the old `layer:` key is still the current "
        "schema and must pass (LINT-05). The fixture supplies its own taxo with "
        "status forced to 'pending' so this proves the pending branch on its own "
        "terms, independent of the real taxonomy.yaml's status (which Phase 3's "
        "atomic commit flips to 'applied').",
    },
    {
        "id": "premature-renamed-key",
        "path": "notes/02-harnesses/fixture-premature-key.md",
        "text": "---\ncategory: 2\n---\n\n# Fixture\n\nPremature rename.\n",
        "expect": "fail",
        "taxo_patch": _with_schema_renames_pending,
        "why": "status is pending — the new `category:` key appearing before "
        "Phase 3's atomic commit fails as premature (ADR-0015 § Sequencing). Same "
        "forced-pending patch as 'old-key-while-pending', for the same reason.",
    },
    {
        "id": "old-key-after-rename-applied",
        "path": "notes/02-harnesses/fixture-old-key-applied.md",
        "text": "---\nlayer: 2\n---\n\n# Fixture\n\nOld key survives after the rename "
        "was supposedly applied.\n",
        "expect": "fail",
        "taxo_patch": _with_schema_renames_applied,
        "why": "the fixture supplies its own taxo with status flipped to 'applied' "
        "— proving the dormant half discriminates NOW, not only in Phase 3; the "
        "surviving old `layer:` key fails as an unapplied decoder.",
    },
    {
        "id": "kind-gate-survives-rename-applied",
        "path": "notes/05-memory/fixture-kind-gate-applied.md",
        "text": "---\ncategory: 5\nkind: agent\n---\n\n# Fixture\n\nBoth renames "
        "applied; stale kind: key must still be caught.\n",
        "expect": "fail",
        "taxo_patch": _with_schema_renames_applied,
        "why": "WR-01/CR-02: after both schema_renames flip to 'applied', a real "
        "category-5 report's frontmatter carries `category:` (post-rename), not "
        "`layer:` — the kind->type scope gate must read whichever key is "
        "currently active (`category` OR `layer`) to still recognize this file "
        "as in-scope and flag the surviving `kind:` key as an unapplied decoder; "
        "a gate hardcoded to `layer` would go silently blind here.",
    },
    {
        "id": "kind-gate-fires-at-category-6",
        "path": "notes/06-extensions/fixture-kind-gate-cat6.md",
        "text": "---\ncategory: 6\nkind: agent\n---\n\n# Fixture\n\nADR-0020 "
        "split: a category-6 report with a stale kind: key must still be caught.\n",
        "expect": "fail",
        "taxo_patch": _with_schema_renames_applied,
        "why": "ADR-0020: the kind->type gate widened to categories 5 and 6 at the "
        "split; without this fixture, --selftest would stay green while the gate "
        "was silently blind to every category-6 report (the WR-01 failure class "
        "at a new number).",
    },
    {
        "id": "kind-colon-in-prose",
        "path": "notes/05-memory/fixture-kind-colon.md",
        "text": "# Fixture\n\nTable stakes in the kind: store + retrieve + MCP.\n",
        "expect": "pass",
        "why": "'kind:' here is ordinary body prose (a list-introducing colon), not "
        "a frontmatter key — check_schema_renames only scans frontmatter and never "
        "sees this line; the deny-list scanner already excludes colon-suffixed "
        "entries from prose. Mirrors the real false positive at "
        "notes/05-memory/ai-memory.md:90.",
    },
    {
        "id": "generated-file-skipped",
        "path": "notes/02-harnesses/fixture-generated-marker.md",
        "text": "<!-- GENERATED by scripts/build-tool-index.py -->\n\n# Fixture\n\n"
        "This file still carries old layer terminology, but it also carries the "
        "generated-output marker.\n",
        "expect": "pass",
        "why": "GENERATED_MARKER makes walk() skip this file before any check ever "
        "sees it, even though notes/* is not itself in exempt_paths.skip_entirely — "
        "the marker is a backstop independent of the path-pattern exemptions "
        "(methodology rule 3).",
    },
    {
        "id": "experiment-log-skipped",
        "path": "experiments/01-fixture-experiment/log.md",
        "text": "# Log\n\nOld layer terminology appears here, appended live during a "
        "run.\n",
        "expect": "pass",
        "why": "'experiments/[0-9]*/log.md' matches exempt_paths.append_only — "
        "never walked at all (D-03, append-only run records).",
    },
    {
        "id": "double-digit-experiment-log-skipped",
        "path": "experiments/10-fixture-experiment/log.md",
        "text": "# Log\n\nOld layer terminology appears here, in a double-digit-"
        "numbered experiment's log.\n",
        "expect": "pass",
        "why": "WR-02: 'experiments/[0-9]*/log.md' must exempt double-digit "
        "experiment numbers too, not just the literal '0' prefix that only "
        "covers 01-09 — the digit-class anchor generalizes past experiment 09.",
    },
    {
        "id": "experiment-protocol-skipped",
        "path": "experiments/01-fixture-experiment/README.md",
        "text": "# Protocol\n\nOld layer terminology, preregistered before the run.\n",
        "expect": "pass",
        "why": "'experiments/[0-9]*/README.md' matches exempt_paths.append_only — "
        "preregistered protocol text is immutable by methodology rule 5 (D-03).",
    },
    {
        "id": "rig-readme-linted",
        "path": "experiments/rig/README.md",
        "text": "# Fixture rig README\n\nStill describes the old layer terminology as "
        "current, since this is a living doc.\n",
        "expect": "fail",
        "why": "experiments/rig/README.md does NOT match "
        "'experiments/[0-9]*/README.md' (no numbered-experiment prefix) — it is a "
        "living doc and D-03 deliberately "
        "keeps it linted like any current-state document, unlike a preregistered "
        "protocol.",
    },
    {
        "id": "articles-draft-linted",
        "path": "articles/fixture-draft.md",
        "text": "# Fixture draft\n\nThis draft still uses the old layer terminology.\n",
        "expect": "fail",
        "why": "articles/ drafts are current-state and swept like any other doc "
        "(D-02, the narrowed pre-sweep-material carve-out) — not exempt merely for "
        "predating the sweep; only exempt_paths' enumerated patterns are exempt.",
    },
    {
        "id": "split-meaning-stack-not-flagged",
        "path": "notes/02-harnesses/fixture-stack.md",
        "text": "# Fixture\n\nHere the tool's stack refers to its top-level grouping "
        "in this survey, not the running composed system.\n",
        "expect": "pass",
        "why": "split_meaning_terms.stack is lint_enforceable: false — no check in "
        "this script ever inspects the word 'stack', so its drift sense is never "
        "flagged; humans catch misuse, per the recorded accepted gap.",
    },
]


# LINT-04b (D-06, vocabulary leakage — prose half): the measurement vocabulary in
# notes/cross-cutting/metrics.md is enforced through the SAME `terms[].deny_list`
# mechanism `check()` already runs above — no separate function, no fuzzy matching,
# LINT-03's model extended in scope only. Deliberately live-but-empty: no measurement
# drift term ("trap score", "attention split", ...) has been observed misused, and
# inventing a deny entry with no evidence behind it would violate methodology rule 4.
# Growing this means adding a term to taxonomy.yaml's `terms:` list with NO code
# change here — that property is what Phase 4 documents.


def run_all_checks(taxo: dict, root: Path = ROOT) -> int:
    """Every drift-class checker, summed. The single dispatch point both `main()` and
    `selftest()` call, so a new checker is wired into both by adding one line here."""
    return (
        check(taxo, root=root)
        + check_reference_formats(taxo, root=root)
        + check_feature_registry(taxo, root=root)
        + check_schema_renames(taxo, root=root)
        + check_unreadable_files(taxo, root=root)
    )


def _assert_harness_discriminates(taxo: dict) -> tuple[int, int]:
    """The `fixture-that-must-discriminate` self-check (T-02-10, methodology rule 5e).

    A harness can exit 0 having done nothing — the risk here is a calibration matrix
    that always reports "pass" (or always "fail") regardless of what a fixture's seeded
    text actually does, making every entry in FIXTURES decorative. This proves the
    want-vs-got comparison that drives the loop above is not vacuous: it takes two
    ALREADY-PROVEN fixtures (one whose real content genuinely fails a check, one whose
    real content genuinely passes), constructs a copy of each with its `expect` field
    deliberately flipped to the WRONG value, and asserts the resulting disagreement
    (`got != expect`) is real — i.e. that `got` tracks the fixture's actual seeded
    content, not merely echoes back whatever `expect` says. A harness that could not
    tell these apart would be exactly the "exited 0, caught nothing" failure mode.

    Returns (checks_run, problems) — folded into --selftest's own N/M totals.
    """
    true_fail = next(fx for fx in FIXTURES if fx["id"] == "denied-term-prose")
    true_pass = next(fx for fx in FIXTURES if fx["id"] == "exempt-path-skipped")
    mislabelled = [
        {**true_fail, "id": "fixture-that-must-discriminate-fail-mislabelled-pass", "expect": "pass"},
        {**true_pass, "id": "fixture-that-must-discriminate-pass-mislabelled-fail", "expect": "fail"},
    ]
    problems = 0
    for fx in mislabelled:
        tmp_root = Path(tempfile.mkdtemp(prefix="check-taxonomy-selftest-"))
        try:
            target = tmp_root / fx["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(fx["text"], encoding="utf-8")
            fx_taxo = fx["taxo_patch"](taxo) if "taxo_patch" in fx else taxo
            got_problems = run_all_checks(fx_taxo, root=tmp_root)
            got = "fail" if got_problems else "pass"
            if got == fx["expect"]:
                # The deliberate mislabel should make got/expect disagree. If they
                # instead agree, either coincidence or (more likely) a vacuous
                # comparison — either way this self-check must name it and fail.
                print(
                    f"ERROR: fixture '{fx['id']}' was mislabelled on purpose "
                    f"(expect={fx['expect']!r}) and the harness did NOT catch the "
                    f"disagreement between seeded content and label — the "
                    f"discrimination check itself is vacuous (methodology 5e, "
                    f"T-02-10)",
                    file=sys.stderr,
                )
                problems += 1
        finally:
            shutil.rmtree(tmp_root, ignore_errors=True)
    return len(mislabelled), problems


def selftest(taxo: dict) -> tuple[int, int]:
    """Run FIXTURES against fresh temp trees, then the discrimination self-check;
    return (fixtures_run, problems)."""
    total_problems = 0
    for fx in FIXTURES:
        tmp_root = Path(tempfile.mkdtemp(prefix="check-taxonomy-selftest-"))
        try:
            target = tmp_root / fx["path"]
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(fx["text"], encoding="utf-8")
            fx_taxo = fx["taxo_patch"](taxo) if "taxo_patch" in fx else taxo
            problems = run_all_checks(fx_taxo, root=tmp_root)
            got = "fail" if problems else "pass"
            if got != fx["expect"]:
                print(
                    f"ERROR: fixture '{fx['id']}' expected {fx['expect']} but got "
                    f"{got} — {fx['why']}",
                    file=sys.stderr,
                )
                total_problems += 1
        finally:
            shutil.rmtree(tmp_root, ignore_errors=True)
    extra_count, extra_problems = _assert_harness_discriminates(taxo)
    total_problems += extra_problems
    return len(FIXTURES) + extra_count, total_problems


def main() -> int:
    taxo = load_taxonomy()
    assert_carveouts_implemented(taxo)
    args = sys.argv[1:]
    valid = {"--check", "--selftest"}
    if len(args) > 1 or (args and args[0] not in valid):
        print("usage: check-taxonomy.py [--check|--selftest]", file=sys.stderr)
        return 2

    if args and args[0] == "--selftest":
        count, problems = selftest(taxo)
        print(f"{count} fixtures run, {problems} problem(s)")
        return 1 if problems else 0

    problems = run_all_checks(taxo)
    files_checked = sum(1 for _ in walk(taxo))
    print(f"{files_checked} files checked, {problems} problem(s)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
